### ISSUE TITLE
download_all_pretrained_weights is failing with "HTTP Error 503: Service Unavailable"

### ISSUE THREAD

**Issue by soichih** [MIC-DKFZ/TractSeg#105]
Hello. I am trying to rebuild our docker container with TractSeg 2.1.1, and I am seeing the following error message when I run `download_all_pretrained_weights` command. 

```
Step 11/13 : RUN HOME=/ download_all_pretrained_weights
 ---> Running in 0d8f04484e1d
Downloading pretrained weights (~140MB) ...
Traceback (most recent call last):
  File "/usr/local/bin/download_all_pretrained_weights", line 32, in <module>
    main()
  File "/usr/local/bin/download_all_pretrained_weights", line 22, in main
    utils.download_pretrained_weights("tract_segmentation")
  File "/usr/local/lib/python3.5/dist-packages/tractseg/libs/utils.py", line 179, in download_pretrained_weights
    data = urlopen(WEIGHTS_URL).read()
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Unavailable
The command '/bin/sh -c HOME=/ download_all_pretrained_weights' returned a non-zero code: 1
```

This used to work fine until recently, so I believe I am running it the right way, has anything changed for 2.1.1?

**Comment by wasserth** [comment]
It should also be working in 2.1.1. I just checked again and it is working for me. Are you using python 3? Is it working if you try again? Zenodo where the weights are downloaded from might not work so nicely with python urllib sometimes.

**Comment by soichih** [comment]
I just ran it again, and it worked this time! Thank you for the suggestion!
