### ISSUE TITLE
TractSeg fails to generate peaks.nii.gz

### ISSUE THREAD

**Issue by soichih** [MIC-DKFZ/TractSeg#106]
I am working on upgrading our script to use TractSeg 2.1.1. I believe I was able to build a new docker container for TractSeg 2.1.1 (with this Dockerfile > https://github.com/brainlife/app-tractseg/blob/master/Dockerfile) 

When I run it, it crashes with the following error message.

```
+ TractSeg -i dwi.nii.gz --raw_diffusion_input --csd_type csd_msmt_5tt --output_type tract_segmentation --keep_intermediate_files --nr_cpus 8 -o . --preprocess
5ttgen: 
5ttgen: Note that this script makes use of commands / algorithms that have relevant articles for citation; INCLUDING FROM EXTERNAL SOFTWARE PACKAGES. Please consult the help page (-help option) for more information.
5ttgen: 
5ttgen: Generated scratch directory: /pylon5/tr4s8pp/shayashi/prod/5ecfedb2fc80c148081f0662/5ecfedb2fc80c11bea1f0665/5ttgen-tmp-QVYA9V/
Command:  mrconvert /pylon5/tr4s8pp/shayashi/prod/5ecfedb2fc80c148081f0662/5ecfedb2fc80c11bea1f0665/T1w_acpc_dc_restore_brain.nii.gz /pylon5/tr4s8pp/shayashi/prod/5ecfedb2fc80c148081f0662/5ecfedb2fc80c11bea1f0665/5ttgen-tmp-QVYA9V/input.mif
5ttgen: Changing to scratch directory (/pylon5/tr4s8pp/shayashi/prod/5ecfedb2fc80c148081f0662/5ecfedb2fc80c11bea1f0665/5ttgen-tmp-QVYA9V/)
Command:  mrconvert input.mif T1.nii -strides -1,+2,+3
Command:  fast T1.nii
Command:  run_first_all -m none -s L_Accu,R_Accu,L_Caud,R_Caud,L_Pall,R_Pall,L_Puta,R_Puta,L_Thal,R_Thal -i T1.nii -o first -b
5ttgen: Generating partial volume images for SGM structures... [=======================================================]
Command:  mrmath [mesh2voxel_*.mif (10 items)] sum - | mrcalc - 1.0 -min all_sgms.mif
Command:  mrthreshold T1_pve_2.nii.gz - -abs 0.001 | maskfilter - connect - -connectivity | mrcalc 1 - 1 -gt -sub remove_unconnected_wm_mask.mif -datatype bit
Command:  mrcalc T1_pve_0.nii.gz remove_unconnected_wm_mask.mif -mult csf.mif
Command:  mrcalc 1.0 csf.mif -sub all_sgms.mif -min sgm.mif
Command:  mrcalc 1.0 csf.mif sgm.mif -add -sub T1_pve_1.nii.gz T1_pve_2.nii.gz -add -div multiplier.mif
Command:  mrcalc multiplier.mif -finite multiplier.mif 0.0 -if multiplier_noNAN.mif
Command:  mrcalc T1_pve_1.nii.gz multiplier_noNAN.mif -mult remove_unconnected_wm_mask.mif -mult cgm.mif
Command:  mrcalc T1_pve_2.nii.gz multiplier_noNAN.mif -mult remove_unconnected_wm_mask.mif -mult wm.mif
Command:  mrcalc 0 wm.mif -min path.mif
Command:  mrcat cgm.mif sgm.mif wm.mif csf.mif path.mif - -axis 3 | mrconvert - combined_precrop.mif -strides +2,+3,+4,+1
Command:  mrmath combined_precrop.mif sum - -axis 3 | mrthreshold - - -abs 0.5 | mrgrid combined_precrop.mif crop result.mif -mask -
Command:  mrconvert result.mif /pylon5/tr4s8pp/shayashi/prod/5ecfedb2fc80c148081f0662/5ecfedb2fc80c11bea1f0665/5TT.nii.gz
Command:  5ttcheck result.mif
5ttgen: Changing back to original directory (/pylon5/tr4s8pp/shayashi/prod/5ecfedb2fc80c148081f0662/5ecfedb2fc80c11bea1f0665)
5ttgen: Deleting scratch directory (/pylon5/tr4s8pp/shayashi/prod/5ecfedb2fc80c148081f0662/5ecfedb2fc80c11bea1f0665/5ttgen-tmp-QVYA9V/)
dwi2response: 
dwi2response: Note that this script makes use of commands / algorithms that have relevant articles for citation. Please consult the help page (-help option) for more information.
dwi2response: 
dwi2response: Generated scratch directory: /pylon5/tr4s8pp/shayashi/prod/5ecfedb2fc80c148081f0662/5ecfedb2fc80c11bea1f0665/dwi2response-tmp-IRD1R4/
dwi2response: Importing DWI data (/pylon5/tr4s8pp/shayashi/prod/5ecfedb2fc80c148081f0662/5ecfedb2fc80c11bea1f0665/Diffusion_MNI.nii.gz)...
dwi2response: Importing mask (/pylon5/tr4s8pp/shayashi/prod/5ecfedb2fc80c148081f0662/5ecfedb2fc80c11bea1f0665/nodif_brain_mask_MNI.nii.gz)...
Command:  mrconvert /pylon5/tr4s8pp/shayashi/prod/5ecfedb2fc80c148081f0662/5ecfedb2fc80c11bea1f0665/5TT.nii.gz /pylon5/tr4s8pp/shayashi/prod/5ecfedb2fc80c148081f0662/5ecfedb2fc80c11bea1f0665/dwi2response-tmp-IRD1R4/5tt.mif
dwi2response: Changing to scratch directory (/pylon5/tr4s8pp/shayashi/prod/5ecfedb2fc80c148081f0662/5ecfedb2fc80c11bea1f0665/dwi2response-tmp-IRD1R4/)
Command:  5ttcheck 5tt.mif
dwi2response: [WARNING] Less than three b-values; response functions will not be applicable in resolving three tissues using MSMT-CSD algorithm
Command:  dwi2tensor dwi.mif - -mask mask.mif | tensor2metric - -fa fa.mif -vector vector.mif
Function: shutil.copy('vector.mif', 'dirs.mif')
Command:  mrtransform 5tt.mif 5tt_regrid.mif -template fa.mif -interp linear
Command:  mrconvert 5tt_regrid.mif - -coord 3 2 -axes 0,1,2 | mrcalc - 0.95 -gt mask.mif -mult wm_mask.mif
Command:  mrconvert 5tt_regrid.mif - -coord 3 0 -axes 0,1,2 | mrcalc - 0.95 -gt fa.mif 0.2 -lt -mult mask.mif -mult gm_mask.mif
Command:  mrconvert 5tt_regrid.mif - -coord 3 3 -axes 0,1,2 | mrcalc - 0.95 -gt fa.mif 0.2 -lt -mult mask.mif -mult csf_mask.mif
dwi2response: Selecting WM single-fibre voxels using 'tournier' algorithm
Command:  dwi2response tournier dwi.mif wm_ss_response.txt -mask wm_mask.mif -voxels wm_sf_mask.mif -scratch /pylon5/tr4s8pp/shayashi/prod/5ecfedb2fc80c148081f0662/5ecfedb2fc80c11bea1f0665/dwi2response-tmp-IRD1R4/

dwi2response: [ERROR] dwi2response tournier dwi.mif wm_ss_response.txt -mask wm_mask.mif -voxels wm_sf_mask.mif -scratch /pylon5/tr4s8pp/shayashi/prod/5ecfedb2fc80c148081f0662/5ecfedb2fc80c11bea1f0665/dwi2response-tmp-IRD1R4/ (msmt_5tt.py:113)
dwi2response: [ERROR] Information from failed command:
dwi2response:
              dwi2response: 
              dwi2response: Note that this script makes use of commands / algorithms that have relevant articles for citation. Please consult the help page (-help option) for more information.
              dwi2response: 
              dwi2response: Generated scratch directory: /pylon5/tr4s8pp/shayashi/prod/5ecfedb2fc80c148081f0662/5ecfedb2fc80c11bea1f0665/dwi2response-tmp-IRD1R4/dwi2response-tmp-DQFPX0/
              dwi2response: Importing DWI data (/pylon5/tr4s8pp/shayashi/prod/5ecfedb2fc80c148081f0662/5ecfedb2fc80c11bea1f0665/dwi2response-tmp-IRD1R4/dwi.mif) and selecting b-values...
              dwi2response: Importing mask (/pylon5/tr4s8pp/shayashi/prod/5ecfedb2fc80c148081f0662/5ecfedb2fc80c11bea1f0665/dwi2response-tmp-IRD1R4/wm_mask.mif)...
              dwi2response: Changing to scratch directory (/pylon5/tr4s8pp/shayashi/prod/5ecfedb2fc80c148081f0662/5ecfedb2fc80c11bea1f0665/dwi2response-tmp-IRD1R4/dwi2response-tmp-DQFPX0/)
              mrstats: [ERROR] Cannot output statistic of interest; no values read (empty mask?)
              
              dwi2response: [ERROR] Error trying to calculate statistics from image 'mask.mif'
dwi2response:
dwi2response: [ERROR] For debugging, inspect contents of scratch directory: /pylon5/tr4s8pp/shayashi/prod/5ecfedb2fc80c148081f0662/5ecfedb2fc80c11bea1f0665/dwi2response-tmp-IRD1R4/
dwi2response: Scratch directory retained; location: /pylon5/tr4s8pp/shayashi/prod/5ecfedb2fc80c148081f0662/5ecfedb2fc80c11bea1f0665/dwi2response-tmp-IRD1R4/
==]
dwi2fod: [ERROR] Unable to open numerical data text file "./RF_WM.txt": No such file or directory
dwi2fod: [ERROR] File "./RF_WM.txt" is not a valid response function file
dwi2fod: [ERROR] MSMT_CSD algorithm expects the first file in each argument pair to be an input response function file
sh2peaks: [ERROR] cannot access file "./WM_FODs.nii.gz": No such file or directory
sh2peaks: [ERROR] error opening image "./WM_FODs.nii.gz"
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/nibabel/loadsave.py", line 42, in load
    stat_result = os.stat(filename)
FileNotFoundError: [Errno 2] No such file or directory: './peaks.nii.gz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/TractSeg", line 400, in <module>
    main()
  File "/usr/local/bin/TractSeg", line 244, in main
    data_img = nib.load(peak_path)
  File "/usr/local/lib/python3.5/dist-packages/nibabel/loadsave.py", line 44, in load
    raise FileNotFoundError("No such file or no access: '%s'" % filename)
FileNotFoundError: No such file or no access: './peaks.nii.gz'
```

I had to update to use mrtrix3:3.0.0, and I am not sure if this might be mrtrix3 issue, but the 5TT.nii.gz (attached) that is generated by TractSeg script seems to be (almost?) blank, and mrtrix3 then fails to create a valid wm_mask.

[5TT.nii.gz](https://github.com/MIC-DKFZ/TractSeg/files/4698581/5TT.nii.gz)

I will run a few more tests to see what is going wrong.. but I wanted to report it to see if @wasserth could give me some hints.

**Comment by wasserth** [comment]
I am always using Mrtrix 3.0 RC3. Might be an issue with newer Mrtrix versions. Maybe the interface of the commands has changed slightly. I will check Mrtrix 3.0.0

**Comment by soichih** [comment]
They changed quite a few things between RC3 and 3.0.0. 

FYI. If I run without --preprocess, it finishes successfully.

**Comment by wasserth** [comment]
I just tested TractSeg with Mrtrix 3.0.0. It works fine.

The problem in your case is the following: You can not use `csd_msmt_5tt` together with `--preprocess`. Because preprocess will only move the Diffusion Image to MNI space but not the T1 image. So 5TT can not properly be generated.

**Comment by soichih** [comment]
@wasserth I see thanks. I tried the "csd" instead of "csd_msmt_5tt", but it failed again with the same error I've reported for #108 

I am guessing I should just stay away from the --preprocess option for now?

**Comment by soichih** [comment]
I ran it without `--preprocess` with `csd_msmt_5tt` option, and I am still seeing the same (similar?) error message.

```
+ TractSeg -i dwi.nii.gz --raw_diffusion_input --csd_type csd_msmt_5tt --output_type tract_segmentation --keep_intermediate_files --nr_cpus 8 -o tractseg_output
5ttgen: 
5ttgen: Note that this script makes use of commands / algorithms that have relevant articles for citation; INCLUDING FROM EXTERNAL SOFTWARE PACKAGES. Please consult the help page (-help option) for more information.
5ttgen: 
5ttgen: Generated scratch directory: /pylon5/tr4s8pp/shayashi/prod/5ed0395afc80c17c191f0e20/5ed815c5529ab4edf084adb3/5ttgen-tmp-3SW4WK/
Command:  mrconvert /pylon5/tr4s8pp/shayashi/prod/5ed0395afc80c17c191f0e20/5ed815c5529ab4edf084adb3/T1w_acpc_dc_restore_brain.nii.gz /pylon5/tr4s8pp/shayashi/prod/5ed0395afc80c17c191f0e20/5ed815c5529ab4edf084adb3/5ttgen-tmp-3SW4WK/input.mif
5ttgen: Changing to scratch directory (/pylon5/tr4s8pp/shayashi/prod/5ed0395afc80c17c191f0e20/5ed815c5529ab4edf084adb3/5ttgen-tmp-3SW4WK/)
Command:  mrconvert input.mif T1.nii -strides -1,+2,+3
Command:  fast T1.nii
Command:  run_first_all -m none -s L_Accu,R_Accu,L_Caud,R_Caud,L_Pall,R_Pall,L_Puta,R_Puta,L_Thal,R_Thal -i T1.nii -o first -b
5ttgen: Generating partial volume images for SGM structures... [=======================================================]
Command:  mrmath [mesh2voxel_*.mif (10 items)] sum - | mrcalc - 1.0 -min all_sgms.mif
Command:  mrthreshold T1_pve_2.nii.gz - -abs 0.001 | maskfilter - connect - -connectivity | mrcalc 1 - 1 -gt -sub remove_unconnected_wm_mask.mif -datatype bit
Command:  mrcalc T1_pve_0.nii.gz remove_unconnected_wm_mask.mif -mult csf.mif
Command:  mrcalc 1.0 csf.mif -sub all_sgms.mif -min sgm.mif
Command:  mrcalc 1.0 csf.mif sgm.mif -add -sub T1_pve_1.nii.gz T1_pve_2.nii.gz -add -div multiplier.mif
Command:  mrcalc multiplier.mif -finite multiplier.mif 0.0 -if multiplier_noNAN.mif
Command:  mrcalc T1_pve_1.nii.gz multiplier_noNAN.mif -mult remove_unconnected_wm_mask.mif -mult cgm.mif
Command:  mrcalc T1_pve_2.nii.gz multiplier_noNAN.mif -mult remove_unconnected_wm_mask.mif -mult wm.mif
Command:  mrcalc 0 wm.mif -min path.mif
Command:  mrcat cgm.mif sgm.mif wm.mif csf.mif path.mif - -axis 3 | mrconvert - combined_precrop.mif -strides +2,+3,+4,+1
Command:  mrmath combined_precrop.mif sum - -axis 3 | mrthreshold - - -abs 0.5 | mrgrid combined_precrop.mif crop result.mif -mask -
Command:  mrconvert result.mif /pylon5/tr4s8pp/shayashi/prod/5ed0395afc80c17c191f0e20/5ed815c5529ab4edf084adb3/tractseg_output/5TT.nii.gz
Command:  5ttcheck result.mif
5ttgen: Changing back to original directory (/pylon5/tr4s8pp/shayashi/prod/5ed0395afc80c17c191f0e20/5ed815c5529ab4edf084adb3)
5ttgen: Deleting scratch directory (/pylon5/tr4s8pp/shayashi/prod/5ed0395afc80c17c191f0e20/5ed815c5529ab4edf084adb3/5ttgen-tmp-3SW4WK/)
dwi2response: 
dwi2response: Note that this script makes use of commands / algorithms that have relevant articles for citation. Please consult the help page (-help option) for more information.
dwi2response: 
dwi2response: Generated scratch directory: /pylon5/tr4s8pp/shayashi/prod/5ed0395afc80c17c191f0e20/5ed815c5529ab4edf084adb3/dwi2response-tmp-NU1KRQ/
dwi2response: Importing DWI data (/pylon5/tr4s8pp/shayashi/prod/5ed0395afc80c17c191f0e20/5ed815c5529ab4edf084adb3/dwi.nii.gz)...
dwi2response: Importing mask (/pylon5/tr4s8pp/shayashi/prod/5ed0395afc80c17c191f0e20/5ed815c5529ab4edf084adb3/tractseg_output/nodif_brain_mask.nii.gz)...
Command:  mrconvert /pylon5/tr4s8pp/shayashi/prod/5ed0395afc80c17c191f0e20/5ed815c5529ab4edf084adb3/tractseg_output/5TT.nii.gz /pylon5/tr4s8pp/shayashi/prod/5ed0395afc80c17c191f0e20/5ed815c5529ab4edf084adb3/dwi2response-tmp-NU1KRQ/5tt.mif
dwi2response: Changing to scratch directory (/pylon5/tr4s8pp/shayashi/prod/5ed0395afc80c17c191f0e20/5ed815c5529ab4edf084adb3/dwi2response-tmp-NU1KRQ/)
Command:  5ttcheck 5tt.mif
dwi2response: [WARNING] Less than three b-values; response functions will not be applicable in resolving three tissues using MSMT-CSD algorithm
Command:  dwi2tensor dwi.mif - -mask mask.mif | tensor2metric - -fa fa.mif -vector vector.mif
Function: shutil.copy('vector.mif', 'dirs.mif')
Command:  mrtransform 5tt.mif 5tt_regrid.mif -template fa.mif -interp linear
Command:  mrconvert 5tt_regrid.mif - -coord 3 2 -axes 0,1,2 | mrcalc - 0.95 -gt mask.mif -mult wm_mask.mif
Command:  mrconvert 5tt_regrid.mif - -coord 3 0 -axes 0,1,2 | mrcalc - 0.95 -gt fa.mif 0.2 -lt -mult mask.mif -mult gm_mask.mif
Command:  mrconvert 5tt_regrid.mif - -coord 3 3 -axes 0,1,2 | mrcalc - 0.95 -gt fa.mif 0.2 -lt -mult mask.mif -mult csf_mask.mif
dwi2response: Selecting WM single-fibre voxels using 'tournier' algorithm
Command:  dwi2response tournier dwi.mif wm_ss_response.txt -mask wm_mask.mif -voxels wm_sf_mask.mif -scratch /pylon5/tr4s8pp/shayashi/prod/5ed0395afc80c17c191f0e20/5ed815c5529ab4edf084adb3/dwi2response-tmp-NU1KRQ/

dwi2response: [ERROR] dwi2response tournier dwi.mif wm_ss_response.txt -mask wm_mask.mif -voxels wm_sf_mask.mif -scratch /pylon5/tr4s8pp/shayashi/prod/5ed0395afc80c17c191f0e20/5ed815c5529ab4edf084adb3/dwi2response-tmp-NU1KRQ/ (msmt_5tt.py:113)
dwi2response: [ERROR] Information from failed command:
dwi2response:
              dwi2response: 
              dwi2response: Note that this script makes use of commands / algorithms that have relevant articles for citation. Please consult the help page (-help option) for more information.
              dwi2response: 
              dwi2response: Generated scratch directory: /pylon5/tr4s8pp/shayashi/prod/5ed0395afc80c17c191f0e20/5ed815c5529ab4edf084adb3/dwi2response-tmp-NU1KRQ/dwi2response-tmp-C00QZL/
              dwi2response: Importing DWI data (/pylon5/tr4s8pp/shayashi/prod/5ed0395afc80c17c191f0e20/5ed815c5529ab4edf084adb3/dwi2response-tmp-NU1KRQ/dwi.mif) and selecting b-values...
              dwi2response: Importing mask (/pylon5/tr4s8pp/shayashi/prod/5ed0395afc80c17c191f0e20/5ed815c5529ab4edf084adb3/dwi2response-tmp-NU1KRQ/wm_mask.mif)...
              dwi2response: Changing to scratch directory (/pylon5/tr4s8pp/shayashi/prod/5ed0395afc80c17c191f0e20/5ed815c5529ab4edf084adb3/dwi2response-tmp-NU1KRQ/dwi2response-tmp-C00QZL/)
              mrstats: [ERROR] Cannot output statistic of interest; no values read (empty mask?)
              
              dwi2response: [ERROR] Error trying to calculate statistics from image 'mask.mif'
dwi2response:
dwi2response: [ERROR] For debugging, inspect contents of scratch directory: /pylon5/tr4s8pp/shayashi/prod/5ed0395afc80c17c191f0e20/5ed815c5529ab4edf084adb3/dwi2response-tmp-NU1KRQ/
dwi2response: Scratch directory retained; location: /pylon5/tr4s8pp/shayashi/prod/5ed0395afc80c17c191f0e20/5ed815c5529ab4edf084adb3/dwi2response-tmp-NU1KRQ/
==]
dwi2fod: [ERROR] Unable to open numerical data text file "tractseg_output/RF_WM.txt": No such file or directory
dwi2fod: [ERROR] File "tractseg_output/RF_WM.txt" is not a valid response function file
dwi2fod: [ERROR] MSMT_CSD algorithm expects the first file in each argument pair to be an input response function file
sh2peaks: [ERROR] cannot access file "tractseg_output/WM_FODs.nii.gz": No such file or directory
sh2peaks: [ERROR] error opening image "tractseg_output/WM_FODs.nii.gz"
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/nibabel/loadsave.py", line 42, in load
    stat_result = os.stat(filename)
FileNotFoundError: [Errno 2] No such file or directory: 'tractseg_output/peaks.nii.gz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/TractSeg", line 400, in <module>
    main()
  File "/usr/local/bin/TractSeg", line 244, in main
    data_img = nib.load(peak_path)
  File "/usr/local/lib/python3.5/dist-packages/nibabel/loadsave.py", line 44, in load
    raise FileNotFoundError("No such file or no access: '%s'" % filename)
FileNotFoundError: No such file or no access: 'tractseg_output/peaks.nii.gz'

```

**Comment by wasserth** [comment]
That is a bit strange. For me these commands are working fine with Mrtrix RC 3 and with Mrtrix 3.0.0:

`TractSeg -i dwi.nii.gz --raw_diffusion_input --csd_type csd --output_type tract_segmentation --keep_intermediate_files --nr_cpus 8 -o tractseg_output --preprocess`

`TractSeg -i dwi.nii.gz --raw_diffusion_input --csd_type csd_msmt_5tt --output_type tract_segmentation --keep_intermediate_files --nr_cpus 8 -o tractseg_output`

If you can send me the dataset where it is not working I can try to have a closer look.

**Comment by wasserth** [comment]
Running `TractSeg -i dwi.nii.gz --raw_diffusion_input --csd_type csd --output_type tract_segmentation --keep_intermediate_files --nr_cpus 8 -o tractseg_output --preprocess` worked fine for me without data, both with Mrtrix 3 RC3 and Mrtrix 3.0.0.

For using `csd_msmt_5tt` I first removed all non-brain tissue from the T1 image. This is not done automatically by TractSeg.
However, even then `csd_msmt_5tt` did not work (both with Mrtrix 3 RC3 and Mrtrix 3.0.0). It gave me the error `[ERROR] CSF tissue mask empty; cannot estimate response function`. It seems that this is rather a problem of Mrtrix than the way Mrtrix is called from within Tractseg.

**Comment by soichih** [comment]
@wasserth Thanks for looking into this. Yes, `--csd-type csd` seems to work.. Although I can get this command to work still (even after running T1 through FSL BET

```
$ TractSeg -i tractseg_output/peaks.nii.gz --output_type TOM --nr_cpus 8 -o tractseg_output
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/joblib/externals/loky/process_executor.py", line 418, in _process_worker
    r = call_item()
  File "/usr/local/lib/python3.5/dist-packages/joblib/externals/loky/process_executor.py", line 272, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.5/dist-packages/joblib/_parallel_backends.py", line 608, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/joblib/parallel.py", line 256, in __call__
    for func, args, kwargs in self.items]
  File "/usr/local/lib/python3.5/dist-packages/joblib/parallel.py", line 256, in <listcomp>
    for func, args, kwargs in self.items]
  File "/usr/local/lib/python3.5/dist-packages/tractseg/libs/peak_utils.py", line 267, in _process_bundle
    bundle_peaks[mask == 0] = 0
IndexError: boolean index did not match indexed array along dimension 0; dimension is 79 but corresponding boolean dimension is 96
"""
```

For `--csd_msmt_5tt` I just realized that my input data is single shell.. it has to be mult-shell, right? Maybe Tractseg can check the input?

**Comment by wasserth** [comment]
I assume the problem is that you used `--preprocess` when generating `tractseg_output/peaks.nii.gz`. Then these peaks are in a different space (MNI space) than the `bundle_segmentations` (converted back to subject space). TOM needs the bundle_segmentations in the same space as the peaks.

Single shell could indeed be the problem when trying to use `csd_msmt_5tt`.
