### ISSUE TITLE
dimension is 79 but corresponding boolean dimension is 96

### ISSUE THREAD

**Issue by soichih** [MIC-DKFZ/TractSeg#108]
Could you tell me what this error message means? (From 2.1.1)

```
+ TractSeg -i tractseg_output/peaks.nii.gz --output_type TOM --nr_cpus 8 -o tractseg_output

  0%|          | 0/144 [00:00<?, ?it/s]
  6%|6         | 9/144 [00:00<00:01, 82.89it/s]
 13%|#3        | 19/144 [00:00<00:01, 85.64it/s]
 20%|##        | 29/144 [00:00<00:01, 87.56it/s]
 27%|##7       | 39/144 [00:00<00:01, 89.08it/s]
 34%|###4      | 49/144 [00:00<00:01, 90.18it/s]
 41%|####      | 59/144 [00:00<00:00, 90.98it/s]
 48%|####7     | 69/144 [00:00<00:00, 91.41it/s]
 55%|#####4    | 79/144 [00:00<00:00, 91.74it/s]
 62%|######1   | 89/144 [00:00<00:00, 92.02it/s]
 69%|######8   | 99/144 [00:01<00:00, 92.26it/s]
 76%|#######5  | 109/144 [00:01<00:00, 92.44it/s]
 83%|########2 | 119/144 [00:01<00:00, 92.51it/s]
 90%|########9 | 129/144 [00:01<00:00, 92.61it/s]
 97%|#########6| 139/144 [00:01<00:00, 92.67it/s]
100%|##########| 144/144 [00:01<00:00, 92.02it/s]
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/joblib/externals/loky/process_executor.py", line 418, in _process_worker
    r = call_item()
  File "/usr/local/lib/python3.5/dist-packages/joblib/externals/loky/process_executor.py", line 272, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.5/dist-packages/joblib/_parallel_backends.py", line 608, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/joblib/parallel.py", line 256, in __call__
    for func, args, kwargs in self.items]
  File "/usr/local/lib/python3.5/dist-packages/joblib/parallel.py", line 256, in <listcomp>
    for func, args, kwargs in self.items]
  File "/usr/local/lib/python3.5/dist-packages/tractseg/libs/peak_utils.py", line 267, in _process_bundle
    bundle_peaks[mask == 0] = 0
IndexError: boolean index did not match indexed array along dimension 0; dimension is 79 but corresponding boolean dimension is 96
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/TractSeg", line 400, in <module>
    main()
  File "/usr/local/bin/TractSeg", line 321, in main
    unit_test=args.test)
  File "/usr/local/lib/python3.5/dist-packages/tractseg/python_api.py", line 242, in run_tractseg
    TOM_dilation, nr_cpus=nr_cpus)
  File "/usr/local/lib/python3.5/dist-packages/tractseg/libs/peak_utils.py", line 273, in mask_and_normalize_peaks
    for idx, bundle in enumerate(bundles))
  File "/usr/local/lib/python3.5/dist-packages/joblib/parallel.py", line 1017, in __call__
    self.retrieve()
  File "/usr/local/lib/python3.5/dist-packages/joblib/parallel.py", line 909, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/usr/local/lib/python3.5/dist-packages/joblib/_parallel_backends.py", line 562, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 405, in result
    return self.__get_result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
IndexError: boolean index did not match indexed array along dimension 0; dimension is 79 but corresponding boolean dimension is 96
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7fb009e65d08>
Traceback (most recent call last):
  File "/usr/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
```

**Comment by wasserth** [comment]
Hmmm, I did not come across this error and can not reproduce it. What shape does `peaks.nii.gz` have and what shape does `tractseg_output/bundle_segmentations/CST_right.nii.gz` have?

**Comment by soichih** [comment]
Here is the mrinfo for peaks.nii.gz

```
hayashis@haswell:~/Downloads $ mrinfo peaks.nii.gz 
************************************************
Image name:          "peaks.nii.gz"
************************************************
  Dimensions:        79 x 94 x 79 x 9
  Voxel size:        2.29 x 2.29 x 2.29 x 1
  Data strides:      [ -1 2 3 4 ]
  Format:            NIfTI-1.1 (GZip compressed)
  Data type:         32 bit float (little endian)
  Intensity scaling: offset = 0, multiplier = 1
  Transform:                    1           0           0      -88.62
                               -0           1           0        -126
                               -0           0           1         -72
  comments:          FSL5.0
  mrtrix_version:    3.0.0
```

CST_right.nii.gz is missing (not in the bundle_segmentations directory), but I see CST_left.nii.gz 

```
************************************************
Image name:          "CST_left.nii.gz"
************************************************
  Dimensions:        96 x 96 x 63
  Voxel size:        2.29 x 2.29 x 2.29
  Data strides:      [ -1 2 3 ]
  Format:            NIfTI-1.1 (GZip compressed)
  Data type:         32 bit float (little endian)
  Intensity scaling: offset = 0, multiplier = 1
  Transform:               0.9999   -0.008286    0.006281      -107.7
                         0.005883       0.949      0.3152      -144.8
                        -0.008573     -0.3152       0.949      -28.41
  comments:          FSL5.0

```

By the way, here is the input dwi shape

```
************************************************
Image name:          "dwi.nii.gz"
************************************************
  Dimensions:        96 x 96 x 63 x 50
  Voxel size:        2.2917 x 2.2917 x 2.3 x 1
  Data strides:      [ -1 2 3 4 ]
  Format:            NIfTI-1.1 (GZip compressed)
  Data type:         32 bit float (little endian)
  Intensity scaling: offset = 0, multiplier = 1
  Transform:               0.9999   -0.008286    0.006281      -107.9
                         0.005883       0.949      0.3152      -144.8
                        -0.008573     -0.3152       0.949       -28.4
  comments:          stable:0004
  mrtrix_version:    3.0_RC3

```

**Comment by wasserth** [comment]
Somehow the peaks have a different shape than the dwi.nii.gz and the CST_left.nii.gz. They should all have the same shape. Are the peaks generated automatically by TractSeg? Using Mrtrix 3.0.0?

**Comment by soichih** [comment]
Yes, the peak was generated by this command

> TractSeg -i dwi.nii.gz --raw_diffusion_input --csd_type csd --output_type tract_segmentation --keep_intermediate_files --nr_cpus 8 -o tractseg_output --preprocess

which uses mrtrix3 internally to create the peak? I only see this in the stdout log.

```
Creating brain mask...
Moving input to MNI space...
Creating peaks (1 of 3)...
Creating peaks (2 of 3)...
Creating peaks (3 of 3)...
Loading weights from: /.tractseg/pretrained_weights_tract_segmentation_v3.npz
Processing direction (1 of 3)
Processing direction (2 of 3)
Processing direction (3 of 3)
Moving output to subject space...
```

Is there a way to make TractSeg to output more log? Like all the commands that it's executing internally?

Note to myself.. the test job on brainlife > https://brainlife.io/project/5d64733db29ac960ca2e797f/process/5ecfee15fc80c18bb01f0669#5ed19e61529ab47d21831f0a

**Comment by wasserth** [comment]
The problem is `--preprocess`. This will move the image to MNI space, run TractSeg and move the results back to subject space. Now when you run `TractSeg -i tractseg_output/peaks.nii.gz --output_type TOM` then you are using the input peaks in MNI space, but for TOM TractSeg also needs the bundle_segmentations (which TractSeg finds automatically) which have been moved back to subject space. Therefore the peaks image and the bundle_segmentations are no longer in the same space which then results in an error.
The `--preprocess` option is not very robust, because it is difficult to adapt to all possible use cases. In most cases it makes more sense if the user does the alignment with MNI space based on his setup.

**Comment by nblauch** [comment]
Hi @wasserth. 

Seems like the best behavior would have the `--preprocess` flag in conjunction with` --output_type TOM` point TractSeg to use the _MNI segmentation masks, producing TOM_MNI, and then convert things back to native space and write to TOM. Would this be possible?

**Comment by wasserth** [comment]
This would be a possible approach. Originally I had not intended to do any preprocessing but leave this to the user. Therefore, adding the preprocess option was a rather quick hack. I will have to spend some more time doing it properly not only of tract segmentation, but also for endings segmentation and TOM.

**Comment by iPsych** [comment]
@nblauch using --process with  --output_type TOM doesn't work.
In the latest (2.9) version, --preprocess make two segmentations folder. one with _MNI and one without _MNI.
as @wasserth mentioned, the TractSeg will automatically refer to the forder without _MNI. so, back up the original folder without _MNI, change the folder name of one with _MNI to without _MNI, TOM process works.
Yes, it's another hacky option.
