### ISSUE TITLE
 could not broadcast input array from shape ..

### ISSUE THREAD

**Issue by soichih** [MIC-DKFZ/TractSeg#12]
I started seeing the following error message. I believe it was working fine before with the input data that I am testing with.

```
Traceback (most recent call last):
  File "/usr/local/bin/TractSeg", line 133, in <module>
    data, flip_done = ImgUtils.flip_peaks_to_correct_orientation_if_needed(data_img)
  File "/usr/local/lib/python2.7/dist-packages/tractseg/libs/ImgUtils.py", line 457, in flip_peaks_to_correct_orientation_if_needed
    peaks = ImgUtils.enfore_shape(peaks, target_shape=(91, 109, 91, 9))
  File "/usr/local/lib/python2.7/dist-packages/tractseg/libs/ImgUtils.py", line 410, in enfore_shape
    data_new[:data.shape[0], :data.shape[1], :data.shape[2]] = data
ValueError: could not broadcast input array from shape (90,108,90,288) into shape (90,108,90,9)

```

Has anything changed?

**Comment by wasserth** [comment]
What version are you using and what is your input command?

**Comment by soichih** [comment]
I was using 1.6. Sorry I wasn't aware of the option name change. Thanks for publishing the change log!

I've updated my command line option and now it's working! Thanks!
