### ISSUE TITLE
TractSeg Container Does Not Have Fury Installed

### ISSUE THREAD

**Issue by smeisler** [MIC-DKFZ/TractSeg#143]
Hello,

When running `plot_tractometry_results` from the master Docker container, I get the following error:

```
ERROR: ld.so: object 'libdlfaker.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libvglfaker.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
/usr/local/lib/python3.7/site-packages/pandas/compat/__init__.py:97: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)
ERROR: ld.so: object 'libdlfaker.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libvglfaker.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
Correcting for comparison of multiple tracts: False
Using 1 manually specified bundles.
Doing group analysis.
Number of subjects:
  group 0: 26
  group 1: 30
  0%|                                                     | 0/1 [00:00<?, ?it/s]/usr/local/lib/python3.7/site-packages/dipy/viz/__init__.py:32: UserWarning: You do not have FURY installed. Some visualization functions might not work for you. For installation instructions, please visit: https://fury.gl/
  "You do not have FURY installed. "
  0%|                                                     | 0/1 [00:06<?, ?it/s]
Traceback (most recent call last):
  File "/usr/local/bin/plot_tractometry_results", line 379, in <module>
    main()
  File "/usr/local/bin/plot_tractometry_results", line 375, in main
    show_color_bar=show_color_bar, save_csv=args.save_csv, y_range=args.range)
  File "/usr/local/bin/plot_tractometry_results", line 275, in plot_tractometry_with_pvalue
    output_path_3D, tracking_format, show_color_bar)
  File "/usr/local/lib/python3.7/site-packages/tractseg/libs/plot_utils.py", line 345, in plot_bundles_with_metric
    from dipy.viz import actor, window
ImportError: cannot import name 'actor' from 'dipy.viz' (/usr/local/lib/python3.7/site-packages/dipy/viz/__init__.py)

```

Could you add Fury to the container please?

Thanks,
Steven

**Comment by wasserth** [comment]
Thank you for reporting this error. I updated the container. Now it should work.
