### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by jgburg** [MIC-DKFZ/TractSeg#144]
Hi all, 

I am running into problems when I run the command
"Tracking -i tractseg_output/peaks.nii.gz -o tractseg_output --nr_fibers 5000"

I get the following output:
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/opt/anaconda3/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/opt/anaconda3/lib/python3.8/site-packages/tractseg/libs/tractseg_prob_tracking.py", line 156, in process_seedpoint
    streamline_part1, length_1 = process_one_way(peaks, streamline1, max_nr_steps, step_size, probabilistic,
  File "/opt/anaconda3/lib/python3.8/site-packages/tractseg/libs/tractseg_prob_tracking.py", line 51, in process_one_way
    dir_raw = get_at_idx(peaks, (last_point[0], last_point[1], last_point[2]))
  File "/opt/anaconda3/lib/python3.8/site-packages/tractseg/libs/tractseg_prob_tracking.py", line 42, in get_at_idx
    return img[int(idx[0]), int(idx[1]), int(idx[2])]
TypeError: 'NoneType' object is not subscriptable
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/anaconda3/bin/Tracking", line 169, in <module>
    main()
  File "/opt/anaconda3/bin/Tracking", line 159, in main
    tracking.track(bundle, input_path, Config.PREDICT_IMG_OUTPUT,
  File "/opt/anaconda3/lib/python3.8/site-packages/tractseg/libs/tracking.py", line 220, in track
    streamlines = tractseg_prob_tracking.track(tom_peaks, max_nr_fibers=nr_fibers, smooth=5,
  File "/opt/anaconda3/lib/python3.8/site-packages/tractseg/libs/tractseg_prob_tracking.py", line 247, in track
    streamlines_tmp = pool.map(partial(process_seedpoint, next_step_displacement_std=next_step_displacement_std,
  File "/opt/anaconda3/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/opt/anaconda3/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
TypeError: 'NoneType' object is not subscriptable

All of my files are Tractseg generated.

Please could I get some guidance on how to fix this?

**Comment by wasserth** [comment]
Unfortunately I can not reproduce this error. First thing you could try: Create a new python virtual environment and only install TractSeg and its dependencies in this environment. Then run TractSeg again.

**Comment by anneleenders** [comment]
Hi all, 

I have the same problem when I'm running the same command. Did you already solve the problem @jgburg?

**Comment by Jayachandra9978** [comment]
I got the same problem. Installing python 3.7 solved the issue.
