### ISSUE TITLE
Plot3D Package incompatability

### ISSUE THREAD

**Issue by smeisler** [MIC-DKFZ/TractSeg#148]
Hi,

It might be worth updating the code for `plot_tractometry_results` or limiting Fury to <= 0.5.1 (along with VTK maybe to a compatible version) given this error:

```
Traceback (most recent call last):
  File "/Users/smeisler/opt/anaconda3/envs/ts/bin/plot_tractometry_results", line 379, in <module>
    main()
  File "/Users/smeisler/opt/anaconda3/envs/ts/bin/plot_tractometry_results", line 375, in main
    show_color_bar=show_color_bar, save_csv=args.save_csv, y_range=args.range)
  File "/Users/smeisler/opt/anaconda3/envs/ts/bin/plot_tractometry_results", line 275, in plot_tractometry_with_pvalue
    output_path_3D, tracking_format, show_color_bar)
  File "/Users/smeisler/opt/anaconda3/envs/ts/lib/python3.7/site-packages/tractseg/libs/plot_utils.py", line 453, in plot_bundles_with_metric
    renderer = window.Renderer()
  File "/Users/smeisler/opt/anaconda3/envs/ts/lib/python3.7/site-packages/fury/deprecator.py", line 193, in deprecated_func
    raise error_class(message)
fury.deprecator.ExpiredDeprecationError: Renderer() deprecated, Please use Scene()instead

* deprecated from version: 0.2.0
* Raises <class 'fury.deprecator.ExpiredDeprecationError'> as of version: 0.6.0
```

This causes the 3D brain renders to crash.

Thanks,
Steven

EDIT: changing FURY to 0.5.1 did prevent crashes, but tracts were no longer added to images. It looks like the _master_ branch has the rendered deprecation fixed and would work with 0.7.0, but a fresh stable 2.2 install does not.

**Comment by wasserth** [comment]
Thank you for this information. I will update the code.

**Comment by wasserth** [comment]
I created a new TractSeg release (2.3) which contains the new changes from master branch. This should work now.
