### ISSUE TITLE
plot_tractometry_results does not run when there are no confounds

### ISSUE THREAD

**Issue by smeisler** [MIC-DKFZ/TractSeg#151]
Hi,

I am on the latest master branch. When I run `plot_tractometry_results` but only include the columns "subject_id" and "target", I get the following error:

```
Traceback (most recent call last):
  File "/om2/user/smeisler/anaconda3/envs/ts/bin/plot_tractometry_results", line 379, in <module>
    main()
  File "/om2/user/smeisler/anaconda3/envs/ts/bin/plot_tractometry_results", line 375, in main
    show_color_bar=show_color_bar, save_csv=args.save_csv, y_range=args.range)
  File "/om2/user/smeisler/anaconda3/envs/ts/bin/plot_tractometry_results", line 142, in plot_tractometry_with_pvalue
    confound_names)
  File "/om2/user/smeisler/anaconda3/envs/ts/bin/plot_tractometry_results", line 80, in correct_for_confounds
    group_data=False).squeeze()
  File "/om2/user/smeisler/anaconda3/envs/ts/lib/python3.7/site-packages/tractseg/libs/metric_utils.py", line 376, in unconfound
    lr = LinearRegression(fit_intercept=True).fit(confound, y)  # lr.coef_: [targets, confounds]
  File "/om2/user/smeisler/anaconda3/envs/ts/lib/python3.7/site-packages/sklearn/linear_model/_base.py", line 519, in fit
    y_numeric=True, multi_output=True)
  File "/om2/user/smeisler/anaconda3/envs/ts/lib/python3.7/site-packages/sklearn/base.py", line 433, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/om2/user/smeisler/anaconda3/envs/ts/lib/python3.7/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "/om2/user/smeisler/anaconda3/envs/ts/lib/python3.7/site-packages/sklearn/utils/validation.py", line 821, in check_X_y
    estimator=estimator)
  File "/om2/user/smeisler/anaconda3/envs/ts/lib/python3.7/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "/om2/user/smeisler/anaconda3/envs/ts/lib/python3.7/site-packages/sklearn/utils/validation.py", line 680, in check_array
    context))
ValueError: Found array with 0 feature(s) (shape=(52, 0)) while a minimum of 1 is required.

```

I could get the code to run by commenting out the call for `values = correct_for_condounds(......)` in the code, but figured something more sustainable is in order. Thanks!

Steven

**Comment by wasserth** [comment]
Thank you for reporting this bug. I just pushed a fix to master.
