### ISSUE TITLE
Issue with bundle-specific tracking 

### ISSUE THREAD

**Issue by duol101** [MIC-DKFZ/TractSeg#166]
Hello!

I am having issues with the bundle-specific tracking part. I have been able to complete all the prior stages, segmentation of bundles, segmentation of start and end regions of bundles, and creation of tract Orientation Maps, but when I try to run bundle-specific tracking I get the error message down below: Tracking -i /Users/nilsvon/Desktop/MRI_data/DTI_MNF/1_101/tractseg_output/peaks.nii.gz -o /Users/nilsvon/Desktop/MRI_data/DTI_MNF/1_101/tractseg_output --nr_fibers 5000 --tracking_format tck 

0%|                                                    | 0/72 [00:02<?, ?it/s]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/nilsvon/opt/anaconda3/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Users/nilsvon/opt/anaconda3/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/Users/nilsvon/opt/anaconda3/lib/python3.8/site-packages/tractseg/libs/tractseg_prob_tracking.py", line 156, in process_seedpoint
    streamline_part1, length_1 = process_one_way(peaks, streamline1, max_nr_steps, step_size, probabilistic,
  File "/Users/nilsvon/opt/anaconda3/lib/python3.8/site-packages/tractseg/libs/tractseg_prob_tracking.py", line 51, in process_one_way
    dir_raw = get_at_idx(peaks, (last_point[0], last_point[1], last_point[2]))
  File "/Users/nilsvon/opt/anaconda3/lib/python3.8/site-packages/tractseg/libs/tractseg_prob_tracking.py", line 42, in get_at_idx
    return img[int(idx[0]), int(idx[1]), int(idx[2])]
TypeError: 'NoneType' object is not subscriptable
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/nilsvon/opt/anaconda3/bin/Tracking", line 169, in <module>
    main()
  File "/Users/nilsvon/opt/anaconda3/bin/Tracking", line 159, in main
    tracking.track(bundle, input_path, Config.PREDICT_IMG_OUTPUT,
  File "/Users/nilsvon/opt/anaconda3/lib/python3.8/site-packages/tractseg/libs/tracking.py", line 220, in track
    streamlines = tractseg_prob_tracking.track(tom_peaks, max_nr_fibers=nr_fibers, smooth=5,
  File "/Users/nilsvon/opt/anaconda3/lib/python3.8/site-packages/tractseg/libs/tractseg_prob_tracking.py", line 247, in track
    streamlines_tmp = pool.map(partial(process_seedpoint, next_step_displacement_std=next_step_displacement_std,
  File "/Users/nilsvon/opt/anaconda3/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/Users/nilsvon/opt/anaconda3/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
TypeError: 'NoneType' object is not subscriptable
(base) nilsvon@Nilss-MacBook-Air ~ %

**Comment by wasserth** [comment]
Are you using the latest master of TractSeg? This contains a bugfix regarding the fiber orientation. This might be related to your problem. You can install the latest master with `pip install --upgrade https://github.com/MIC-DKFZ/TractSeg/archive/master.zip`

If this does not solve your problem I would try to move your subjects to MNI space (. When your images are flipped with respect to MNI space the tracking code might run into problems. (see https://github.com/MIC-DKFZ/TractSeg#aligning-image-to-mni-space)

**Comment by duol101** [comment]
Thank you for your prompt reply!

I have aligned tried this on one subject now, aligning to MNI space using --preprocess and it works up until: 

Tracking -i /Users/nilsvon/Desktop/MRI_data/DTI_MNF/1_101/tractseg_output/peaks.nii.gz -o /Users/nilsvon/Desktop/MRI_data/DTI_MNF/1_101/tractseg_output --nr_fibers 5000 --tracking_format tck 

Since aligning has seemed to work I now have the files bundle_segmentations, bundle_segmentations_MNI, endings_segmentations, endings_segmentations_MNI, TOM, TOM_MNI, in my tractseg_output. Is there something I need to specify in the Tracking command in order to have in run on the MNI files? 

Best regards,

Nils

**Comment by duol101** [comment]
Edit: I tried moving the TOM folder outside of the tractseg_output folder and renamed the TOM_MNI folder to TOM in order to have it run on that, but I still run into the same error message. In both cases the terminal seems to be working for a bit, it even creates an empty TOM_trackings folder in tractseg_output, but then stops and gives me the error message.

**Comment by wasserth** [comment]
This is a bit confusing unfortunately. For running the Tracking on the MNI data you have to do the following: 
Remove all the non-MNI folders from `tractseg_output`. Then rename bundle_segmentations_MNI to bundle_segmentations, endings_segmentations_MNI to endings_segmentations and TOM_MNI to TOM. Then run `Tracking -i /Users/nilsvon/Desktop/MRI_data/DTI_MNF/1_101/tractseg_output/peaks.nii.gz -o /Users/nilsvon/Desktop/MRI_data/DTI_MNF/1_101/tractseg_output --nr_fibers 5000 --tracking_format tck`

**Comment by duol101** [comment]
Just did all of that, still getting this error:

0%|                                                    | 0/72 [00:02<?, ?it/s]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/nilsvon/opt/anaconda3/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Users/nilsvon/opt/anaconda3/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/Users/nilsvon/opt/anaconda3/lib/python3.8/site-packages/tractseg/libs/tractseg_prob_tracking.py", line 156, in process_seedpoint
    streamline_part1, length_1 = process_one_way(peaks, streamline1, max_nr_steps, step_size, probabilistic,
  File "/Users/nilsvon/opt/anaconda3/lib/python3.8/site-packages/tractseg/libs/tractseg_prob_tracking.py", line 51, in process_one_way
    dir_raw = get_at_idx(peaks, (last_point[0], last_point[1], last_point[2]))
  File "/Users/nilsvon/opt/anaconda3/lib/python3.8/site-packages/tractseg/libs/tractseg_prob_tracking.py", line 42, in get_at_idx
    return img[int(idx[0]), int(idx[1]), int(idx[2])]
TypeError: 'NoneType' object is not subscriptable
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/nilsvon/opt/anaconda3/bin/Tracking", line 169, in <module>
    main()
  File "/Users/nilsvon/opt/anaconda3/bin/Tracking", line 159, in main
    tracking.track(bundle, input_path, Config.PREDICT_IMG_OUTPUT,
  File "/Users/nilsvon/opt/anaconda3/lib/python3.8/site-packages/tractseg/libs/tracking.py", line 220, in track
    streamlines = tractseg_prob_tracking.track(tom_peaks, max_nr_fibers=nr_fibers, smooth=5,
  File "/Users/nilsvon/opt/anaconda3/lib/python3.8/site-packages/tractseg/libs/tractseg_prob_tracking.py", line 247, in track
    streamlines_tmp = pool.map(partial(process_seedpoint, next_step_displacement_std=next_step_displacement_std,
  File "/Users/nilsvon/opt/anaconda3/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/Users/nilsvon/opt/anaconda3/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
TypeError: 'NoneType' object is not subscriptable
(base) nilsvon@Nilss-MacBook-Air ~ %

**Comment by wasserth** [comment]
To be able to further debug this problem I would need to have a look at the data. Would it be possible to send me the Diffusion image?

**Comment by duol101** [comment]
Yes just one moment, I am checking with the owner of the data if I am allowed to share it with you!

**Comment by duol101** [comment]
I can't send you the data at this time but thank you for all your help so far! I might reach out again if I get clearance to send the data.
