### ISSUE TITLE
dwi2response error when using raw dwi data as input for tractseg

### ISSUE THREAD

**Issue by CarolynMcNabb** [MIC-DKFZ/TractSeg#175]
Hello,

I am trying to use some preprocessed (but essentially raw) data as input into TractSeg and am coming up with errors similar to those reported in [this closed issue](https://github.com/MIC-DKFZ/TractSeg/issues/30). I am using the version of mrtrix that you suggested (Mrtrix 3.0 RC3) but the error persists. I wondered if you could please take a look? 

Thank you so much,
Carolyn

**Error message:**

```
TractSeg -i 349_380101866/dwi_349_380101866_alspac_TD_III.nii.gz -o 349_380101866/tractseg_output --bvals 349_380101866/dwi_349_380101866_alspac_TD_III.bval --bvecs 349_380101866/dwi_349_380101866_alspac_TD_III.bvec --raw_diffusion_input --output_type tract_segmentation
Creating peaks (1 of 3)...
Traceback (most recent call last):
  File "/cubric/software/mrtrix/bin/dwi2response", line 104, in <module>
    if int(image.statistic('mask.mif', 'count', 'mask.mif')) == 0:
ValueError: invalid literal for int() with base 10: '212854  212854  212854  212854  212854  212854  212854  212854  212854  212854  212854  212854  212854  212854  212854  212854  212854  212854  212854  212854  212854  212854  212854  212854  212854  '
Creating peaks (2 of 3)...
dwi2fod: [ERROR] no data in matrix file "349_380101866/tractseg_output/response.txt"
dwi2fod: [ERROR] CSD algorithm expects second argument to be the input response function file
Creating peaks (3 of 3)...
sh2peaks: [ERROR] cannot access file "349_380101866/tractseg_output/WM_FODs.nii.gz": No such file or directory
sh2peaks: [ERROR] error opening image "349_380101866/tractseg_output/WM_FODs.nii.gz"
Traceback (most recent call last):
  File "/home/sapcm15/.local/lib/python3.6/site-packages/nibabel/loadsave.py", line 42, in load
    stat_result = os.stat(filename)
FileNotFoundError: [Errno 2] No such file or directory: '349_380101866/tractseg_output/peaks.nii.gz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sapcm15/.local/bin/TractSeg", line 417, in <module>
    main()
  File "/home/sapcm15/.local/bin/TractSeg", line 255, in main
    data_img = nib.load(peak_path)
  File "/home/sapcm15/.local/lib/python3.6/site-packages/nibabel/loadsave.py", line 44, in load
    raise FileNotFoundError(f"No such file or no access: '{filename}'")
FileNotFoundError: No such file or no access: '349_380101866/tractseg_output/peaks.nii.gz'

```

**Comment by wasserth** [comment]
The error is within dwi2response (`ValueError: invalid literal for int() with base 10: '212854  212854  212854  212854  212854  212854  212854  212854  212854  212854  212854  212854  212854  212854  212854  212854  212854  212854  212854  212854  212854  212854  212854  212854  212854  '`). Unfortunately I am not familiar with this error. Maybe your preprocessing changed the data in a bad way. I would try doing it again without preprocessing.
If that does not help you would have to ask again in the mrtrix forum about this error.

**Comment by CarolynMcNabb** [comment]
Hi @wasserth,

I have found the issue (thanks to [this post](https://community.mrtrix.org/t/dwi2response-tournier-error-invalid-literal-for-int-base-10/847/9) and have hacked the tractseg code to get around it. The problem is that mrtrix is expecting to see a 3D nodif_brain_mask image but tractseg is producing a 4D image (mine had 266 volumes for instance). So I just took the first volume and overwrote the nodif_brain_mask image with that.

In `preprocessing.py` I added a line of code to perform `fslroi` on the *nodif_brain_mask.nii.gz* image:
```
def create_brain_mask(input_file, output_dir):
    print("Creating brain mask...")

    input_dir = os.path.dirname(input_file)
    input_file_without_ending = os.path.basename(input_file).split(".")[0]
    os.system("bet " + join(input_dir, input_file_without_ending) + " " +
              output_dir + "/nodif_brain_mask.nii.gz  -f 0.3 -g 0 -m")
    os.system("rm " + output_dir + "/nodif_brain_mask.nii.gz")  # masked brain
    os.system("mv " + output_dir + "/nodif_brain_mask_mask.nii.gz " + output_dir + "/nodif_brain_mask.nii.gz")
    #Carolyn's hack for removing 4D component of nodif_brain_mask.nii.gz
    os.system("fslroi " + output_dir + "/nodif_brain_mask.nii.gz " + output_dir + "/nodif_brain_mask.nii.gz " + "0 " + "1" )
    return join(output_dir, "nodif_brain_mask.nii.gz")

```
It works well now.

Hope this is helpful and of use to anyone else facing this problem.

Carolyn

**Comment by wasserth** [comment]
Thank you for this update! I will see if I can include it in the tractSeg code.

**Comment by wasserth** [comment]
The problem seems to be the following: With the older FSL versions bet used to create a 3D Volume. The newest FSL bet changed the behaviour and now creates a 4D Volume if the input also was a 4D volume.
I incorporated your change into the TractSeg code base (see newest master).

**Comment by CarolynMcNabb** [comment]
Thanks so much @wasserth. Sneaky FSL!
