### ISSUE TITLE
ImportError: cannot import name 'compress_streamlines' from 'dipy.tracking.streamline' 

### ISSUE THREAD

**Issue by Nat-Sci** [MIC-DKFZ/TractSeg#178]
Hi, experts,

When I type 'TractSeg  --help', an error emerges.
My dipy version is 1.5.0, and should I degrade it to 1.4.1?

Thanks!

Traceback (most recent call last):
  File "/public/home/liufh/anaconda3/envs/dwi/bin/TractSeg", line 20, in <module>
    from tractseg.libs import plot_utils
  File "/public/home/liufh/anaconda3/envs/dwi/lib/python3.7/site-packages/tractseg/libs/plot_utils.py", line 22, in <module>
    from tractseg.libs import fiber_utils
  File "/public/home/liufh/anaconda3/envs/dwi/lib/python3.7/site-packages/tractseg/libs/fiber_utils.py", line 10, in <module>
    from dipy.tracking.streamline import compress_streamlines as compress_streamlines_dipy
ImportError: cannot import name 'compress_streamlines' from 'dipy.tracking.streamline'

**Comment by Nat-Sci** [comment]
> pip install https://github.com/MIC-DKFZ/TractSeg/archive/master.zip
Hi, Jakob Wasserthal

Yeah, master repo. works. 

Thanks,
Feihong Liu
