### ISSUE TITLE
TractSeg bedpostX out of memoryy

### ISSUE THREAD

**Issue by dyhan316** [MIC-DKFZ/TractSeg#184]
In the following bedpostX folder, I tried running `TractSeg -i dyads1.nii.gz`.
![image](https://user-images.githubusercontent.com/34816251/173292812-9806ef3d-253c-4f0c-8773-446b1cd9c176.png)

However, the following error was output : 

```
BedpostX dyads detected. Will automatically combine dyads1+2[+3].
Loading weights from: /home/connectome/dyhan316/.tractseg/pretrained_weights_tract_segmentation_v3.npz
Traceback (most recent call last):
  File "/home/connectome/dyhan316/.conda/envs/TRACTSEG/bin/TractSeg", line 417, in <module>
    main()
  File "/home/connectome/dyhan316/.conda/envs/TRACTSEG/bin/TractSeg", line 334, in main
    unit_test=args.test)
  File "/home/connectome/dyhan316/.conda/envs/TRACTSEG/lib/python3.7/site-packages/tractseg/python_api.py", line 157, in run_tractseg
    model = BaseModel(Config, inference=True)
  File "/home/connectome/dyhan316/.conda/envs/TRACTSEG/lib/python3.7/site-packages/tractseg/models/base_model.py", line 78, in __init__
    net = self.net.to(self.device)
  File "/home/connectome/dyhan316/.conda/envs/TRACTSEG/lib/python3.7/site-packages/torch/nn/modules/module.py", line 907, in to
    return self._apply(convert)
  File "/home/connectome/dyhan316/.conda/envs/TRACTSEG/lib/python3.7/site-packages/torch/nn/modules/module.py", line 578, in _apply
    module._apply(fn)
  File "/home/connectome/dyhan316/.conda/envs/TRACTSEG/lib/python3.7/site-packages/torch/nn/modules/module.py", line 578, in _apply
    module._apply(fn)
  File "/home/connectome/dyhan316/.conda/envs/TRACTSEG/lib/python3.7/site-packages/torch/nn/modules/module.py", line 601, in _apply
    param_applied = fn(param)
  File "/home/connectome/dyhan316/.conda/envs/TRACTSEG/lib/python3.7/site-packages/torch/nn/modules/module.py", line 905, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

```

I looked at `nvidia-smi` to check if it really is a memory issue, but as the picture below shows, there are plenty of idle gpus... Could anyone explain how I can resolve this? Thank you!
![image](https://user-images.githubusercontent.com/34816251/173293103-895ffdf5-a3bf-43b4-973b-aacceb0e21f1.png)

**Comment by wasserth** [comment]
Does tractseg for normal input (no bedpostX) work without any memory errors?

**Comment by dyhan316** [comment]
Thank you for the reply! When done with just preprocessed dwi data, I get, 

```
Creating brain mask...
Warning: An input intended to be a single 3D volume has multiple timepoints. Input will be truncated to first volume, but this functionality is deprecated and will be removed in a future release.
Creating peaks (1 of 3)...
sh: 1: dwi2response: not found
Creating peaks (2 of 3)...
sh: 1: dwi2fod: not found
Creating peaks (3 of 3)...
sh: 1: sh2peaks: not found
Traceback (most recent call last):
  File "/home/connectome/dyhan316/.conda/envs/TRACTSEG/lib/python3.7/site-packages/nibabel/loadsave.py", line 42, in load
    stat_result = os.stat(filename)
FileNotFoundError: [Errno 2] No such file or directory: 'tractseg_output/peaks.nii.gz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/connectome/dyhan316/.conda/envs/TRACTSEG/bin/TractSeg", line 417, in <module>
    main()
  File "/home/connectome/dyhan316/.conda/envs/TRACTSEG/bin/TractSeg", line 255, in main
    data_img = nib.load(peak_path)
  File "/home/connectome/dyhan316/.conda/envs/TRACTSEG/lib/python3.7/site-packages/nibabel/loadsave.py", line 44, in load
    raise FileNotFoundError(f"No such file or no access: '{filename}'")
FileNotFoundError: No such file or no access: 'tractseg_output/peaks.nii.gz'

```

**Comment by dyhan316** [comment]
Thank you for the response! 

The thing is, mrtrix3 is installed on my conda environment, but it still gives me an error (

```
Creating brain mask...
Warning: An input intended to be a single 3D volume has multiple timepoints. Input will be truncated to first volume, but this functionality is deprecated and will be removed in a future release.
Creating peaks (1 of 3)...

dwi2response: [ERROR] mrconvert /scratch/connectome/dyhan316/WECANDOIT/tract_seg_try/sub-101/dwi/sub-101_acq-mb3multishell_dir-LR_dwi.nii.gz - -strides 0,0,0,1 -fslgrad /scratch/connectome/dyhan316/WECANDOIT/tract_seg_try/sub-101/dwi/sub-101_acq-mb3multishell_dir-LR_dwi.bvecs /scratch/connectome/dyhan316/WECANDOIT/tract_seg_try/sub-101/dwi/sub-101_acq-mb3multishell_dir-LR_dwi.bvals | dwiextract - /scratch/connectome/dyhan316/WECANDOIT/tract_seg_try/sub-101/dwi/dwi2response-tmp-YMQXX6/dwi.mif -singleshell -no_bzero (dwi2response:91)
dwi2response: [ERROR] Information from failed command:
dwi2response:
              mrconvert: [ERROR] input file "/scratch/connectome/dyhan316/WECANDOIT/tract_seg_try/sub-101/dwi/sub-101_acq-mb3multishell_dir-LR_dwi.bvecs" for option "-fslgrad" not found
              dwiextract: [ERROR] no filename supplied to standard input (broken pipe?)
              dwiextract: [ERROR] error opening image "-"
dwi2response:
dwi2response: [ERROR] For debugging, inspect contents of scratch directory: /scratch/connectome/dyhan316/WECANDOIT/tract_seg_try/sub-101/dwi/dwi2response-tmp-YMQXX6/
Creating peaks (2 of 3)...
dwi2fod: [ERROR] input file "sub-101_acq-mb3multishell_dir-LR_dwi.bvecs" for option "-fslgrad" not found
Creating peaks (3 of 3)...
sh2peaks: [ERROR] cannot access file "tractseg_output/WM_FODs.nii.gz": No such file or directory
sh2peaks: [ERROR] error opening image "tractseg_output/WM_FODs.nii.gz"
Traceback (most recent call last):
  File "/home/connectome/dyhan316/.conda/envs/TRACTSEG/lib/python3.7/site-packages/nibabel/loadsave.py", line 42, in load
    stat_result = os.stat(filename)
FileNotFoundError: [Errno 2] No such file or directory: 'tractseg_output/peaks.nii.gz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/connectome/dyhan316/.conda/envs/TRACTSEG/bin/TractSeg", line 417, in <module>
    main()
  File "/home/connectome/dyhan316/.conda/envs/TRACTSEG/bin/TractSeg", line 255, in main
    data_img = nib.load(peak_path)
  File "/home/connectome/dyhan316/.conda/envs/TRACTSEG/lib/python3.7/site-packages/nibabel/loadsave.py", line 44, in load
    raise FileNotFoundError(f"No such file or no access: '{filename}'")
FileNotFoundError: No such file or no access: 'tractseg_output/peaks.nii.gz'


```
