### ISSUE TITLE
Error could not find file when plot_tractometry_results via docker

### ISSUE THREAD

**Issue by Suming-zhang** [MIC-DKFZ/TractSeg#209]
Dear @wasserth 
   hello!
I am pretty new with TractSeg and I am trying to get plots of Tractometry results via docker. as for my data, I put the Tractometry.csv file under each subject's folder with the absolute path "/media/suming/Elements/OCD2021_DATA/subject_id/",which subject_id is the name of everysubject's folder, just like my subject.txt named NOCD_subject.txt file names. 
however an error "  No such file or directory: /media/suming/Elements/OCD2021_DATA/sub-KQELLKMC002\t0\t25\t0/Tractometry.csv" happend. I am confused about the reason. 
could anyone give some advice? thanks a lot

  below is my docker code and my subject.txt
-------my docker code--------------
sudo docker run -v /media/suming/Elements/OCD2021_DATA:/tractseg -v /media/suming/Elements/OCD2021_DATA/out_statis:/output -t wasserth/tractseg_container:master plot_tractometry_results -i /tractseg/NOCD_subject.txt -o /output/tractometry_result.png --mc

------------my subject.txt file-----
[NOCD_subject.txt](https://github.com/MIC-DKFZ/TractSeg/files/9862058/NOCD_subject.txt)

**Comment by wasserth** [comment]
Your subjects in the subject.txt file are sometimes separated with spaces (which is correct) and somtimes separated with tabs (which is not correct). If you change the tabs to spaces it might solve your problem.

**Comment by Suming-zhang** [comment]
> Your subjects in the subject.txt file are sometimes separated with spaces (which is correct) and somtimes separated with tabs (which is not correct). If you change the tabs to spaces it might solve your problem.

Dear @wasserth 
  much thanks for your suggestion! It really works after I fixed the error about "spaces" and "tabs". however, I met another bug when re-running my docker code as mentioned above. the error reported "no file found" but in fact,the file named "Tractometry.csv" just exist in the correct absolute pathway(every subject's folder). could you please give me any help kindly? thanks a lot
best wishes!

suming

below is the error report
----------------------------error---------------------------------------------------
/usr/local/lib/python3.7/site-packages/pandas/compat/__init__.py:124: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)
Correcting for comparison of multiple tracts: True
Using 20 manually specified bundles.
Doing group analysis.
Number of subjects:
  group 0: 45
  group 1: 66
Traceback (most recent call last):
  File "/usr/local/bin/plot_tractometry_results", line 382, in <module>
    main()
  File "/usr/local/bin/plot_tractometry_results", line 370, in main
    raw = np.loadtxt(base_path.replace("SUBJECT_ID", subject), delimiter=";", skiprows=1).transpose()
  File "/usr/local/lib/python3.7/site-packages/numpy/lib/npyio.py", line 1067, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/usr/local/lib/python3.7/site-packages/numpy/lib/_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/usr/local/lib/python3.7/site-packages/numpy/lib/_datasource.py", line 531, in open
    encoding=encoding, newline=newline)
FileNotFoundError: [Errno 2] No such file or directory: '/media/suming/Elements/OCD2021_DATA/sub-KQELLKMC002/Tractometry.csv'
----------------------------------------------

**Comment by wasserth** [comment]
If you are running the code via docker maybe the mounting of the directories into docker is incorrect.  (you specify this via the `-v` argument when calling docker run)

**Comment by Suming-zhang** [comment]
> If you are running the code via docker maybe the mounting of the directories into docker is incorrect. (you specify this via the `-v` argument when calling docker run)

Dear @wasserth 
 thanks for your effort for giving helpful advice! I succeed to run smoothly  after following your suggestion. I met another error when plot 3D fiber. my code is like this" plot_tractometry_results -i subjects.txt -o tractometry_3D.png --mc --plot3D metric --tracking_format tck --tracking_dir /media/suming/Elements/OCD2021_DATA/sub-P057/tractseg_output" and the error said the index is out of bounds for axis 0 with size 156(as below).  I am confused about the reason of error, could you please give any advice?
thanks a lot!

------------error-------------------------
Correcting for comparison of multiple tracts: True
Using 32 manually specified bundles.
Doing group analysis.
Number of subjects:
  group 0: 41
  group 1: 52
  0%|                                                                                                                     | 0/32 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "/usr/local/anaconda3/bin/plot_tractometry_results", line 382, in <module>
    main()
  File "/usr/local/anaconda3/bin/plot_tractometry_results", line 373, in main
    plot_tractometry_with_pvalue(values, meta_data, all_bundles, selected_bundles, args.output_path,
  File "/usr/local/anaconda3/bin/plot_tractometry_results", line 277, in plot_tractometry_with_pvalue
    plot_utils.plot_bundles_with_metric(tracking_path, ending_path, mask_path, bundle, metric,
  File "/usr/local/anaconda3/lib/python3.9/site-packages/tractseg/libs/plot_utils.py", line 395, in plot_bundles_with_metric
    streamlines = fiber_utils.orient_to_same_start_region(streamlines, beginnings)
  File "/usr/local/anaconda3/lib/python3.9/site-packages/tractseg/libs/fiber_utils.py", line 470, in orient_to_same_start_region
    if beginnings[int(startpoint[0]), int(startpoint[1]), int(startpoint[2])] == 0:
IndexError: index -399 is out of bounds for axis 0 with size 156
-----------------------------------------------
best wishes
suming

**Comment by Suming-zhang** [comment]
> This is a known issue which was solved in the latest master branch. Do you use the latest container?
dear @wasserth :
  thanks for you help. but I have already installed the latest master version via "pip install --upgrade TractSeg".when I run the code above('plot_tractometry_results -i subjects.txt -o tractometry_3D.png --mc --plot3D metric --tracking_format tck --tracking_dir /media/suming/Elements/OCD2021_DATA/sub-P057/tractseg_output'), then another error still unfortunately happen. could you please give any help?

-----new error------------
WARNING: steamline startpoint out of image. Discarding this streamline.
  0%|                                                    | 0/32 [00:03<?, ?it/s]
Traceback (most recent call last):
  File "/usr/local/anaconda3/bin/plot_tractometry_results", line 384, in <module>
    main()
  File "/usr/local/anaconda3/bin/plot_tractometry_results", line 375, in main
    plot_tractometry_with_pvalue(values, meta_data, all_bundles, selected_bundles, args.output_path,
  File "/usr/local/anaconda3/bin/plot_tractometry_results", line 277, in plot_tractometry_with_pvalue
    plot_utils.plot_bundles_with_metric(tracking_path, ending_path, mask_path, bundle, metric,
  File "/usr/local/anaconda3/lib/python3.9/site-packages/tractseg/libs/plot_utils.py", line 422, in plot_bundles_with_metric
    _, segment_idxs = cKDTree(centroids.get_data(), 1, copy_data=True).query(streamlines, k=1)
  File "ckdtree.pyx", line 567, in scipy.spatial.ckdtree.cKDTree.__init__
ValueError: data must be 2 dimensions
--------------
thanks for any help

suming

**Comment by wasserth** [comment]
Does it work if you try it without `--plot3D metric`?

**Comment by Suming-zhang** [comment]
> Does it work if you try it without `--plot3D metric`?

yes, if delete "--plot3D metric" the code run smoothly~ Is there any conflict between "plot 3D" with the other code?

thanks a lot
