### ISSUE TITLE
Index Error while training own Model

### ISSUE THREAD

**Issue by mrrestre** [MIC-DKFZ/TractSeg#215]
Hi I have being trying to train my own model and come to the following issue:
When training the model and trying to validate, do you have any idea what could be wrong? I have checked all array sizes and it looks good I don’t get where this IndexError is coming from.

Also, I would like to know if there is any way I can run the training (ExpRunner --config my_custom_experiment) on debug modus. 
Here are the errors for some more context
```
Hyperparameters:
{'BATCH_NORM': False,
 'BATCH_SIZE': 47,
 'BEST_EPOCH': 0,
 'BEST_EPOCH_SELECTION': 'f1',
 'CALC_F1': True,
 'CLASSES': 'All',
 'CSD_RESOLUTION': 'LOW',
 'CV_FOLD': 0,
 'DATASET': 'HCP',
 'DATASET_FOLDER': 'HCP',
 'DATA_AUGMENTATION': True,
 'DAUG_ALPHA': (90.0, 120.0),
 'DAUG_BLUR_SIGMA': (0, 1),
 'DAUG_ELASTIC_DEFORM': True,
 'DAUG_FLIP_PEAKS': False,
 'DAUG_GAUSSIAN_BLUR': True,
 'DAUG_INFO': '-',
 'DAUG_MIRROR': False,
 'DAUG_NOISE': True,
 'DAUG_NOISE_VARIANCE': (0, 0.05),
 'DAUG_RESAMPLE': False,
 'DAUG_RESAMPLE_LEGACY': False,
 'DAUG_ROTATE': False,
 'DAUG_ROTATE_ANGLE': (-0.2, 0.2),
 'DAUG_SCALE': True,
 'DAUG_SIGMA': (9.0, 11.0),
 'DIM': '2D',
 'DROPOUT_SAMPLING': False,
 'EPOCH_MULTIPLIER': 1,
 'EXPERIMENT_TYPE': 'tract_segmentation',
 'EXP_MULTI_NAME': '',
 'EXP_NAME': 'my_custom_experiment',
 'EXP_PATH': '/home/AR/TractSeg/hcp_exp/my_custom_experiment_x39',
 'FEATURES_FILENAME': 'peaks',
 'FLIP_OUTPUT_PEAKS': False,
 'FP16': True,
 'GET_PROBS': False,
 'INFO': '-',
 'INPUT_DIM': (144, 144),
 'INPUT_RESCALING': False,
 'KEEP_INTERMEDIATE_FILES': False,
 'LABELS_FILENAME': 'bundle_masks',
 'LABELS_FOLDER': 'bundle_masks',
 'LABELS_TYPE': 'int',
 'LEARNING_RATE': 0.001,
 'LOAD_WEIGHTS': False,
 'LOSS_FUNCTION': 'default',
 'LOSS_WEIGHT': None,
 'LOSS_WEIGHT_LEN': -1,
 'LR_SCHEDULE': True,
 'LR_SCHEDULE_MODE': 'min',
 'LR_SCHEDULE_PATIENCE': 20,
 'METRIC_TYPES': ['loss', 'f1_macro'],
 'MODEL': 'UNet_Pytorch_DeepSup',
 'MULTI_PARENT_PATH': '/home/AR/TractSeg/hcp_exp/',
 'NORMALIZE_DATA': True,
 'NORMALIZE_PER_CHANNEL': False,
 'NR_CPUS': -1,
 'NR_OF_CLASSES': 74,
 'NR_OF_GRADIENTS': 9,
 'NR_SLICES': 1,
 'NUM_EPOCHS': 250,
 'ONLY_VAL': False,
 'OPTIMIZER': 'Adamax',
 'OUTPUT_MULTIPLE_FILES': False,
 'PAD_TO_SQUARE': True,
 'PEAK_DICE_LEN_THR': 0.05,
 'PEAK_DICE_THR': [0.95],
 'PREDICT_IMG': False,
 'PREDICT_IMG_OUTPUT': None,
 'PRINT_FREQ': 20,
 'P_SAMP': 1.0,
 'RESET_LAST_LAYER': False,
 'RESOLUTION': '1.25mm',
 'SAVE_WEIGHTS': True,
 'SEGMENT': False,
 'SEG_INPUT': 'Peaks',
 'SLICE_DIRECTION': 'y',
 'SPATIAL_TRANSFORM': 'SpatialTransform',
 'TEST': False,
 'TEST_TIME_DAUG': False,
 'THRESHOLD': 0.5,
 'TRACTSEG_DIR': 'tractseg_output',
 'TRAIN': True,
 'TRAINING_SLICE_DIRECTION': 'xyz',
 'TYPE': 'single_direction',
 'UNET_NR_FILT': 64,
 'UPSAMPLE_TYPE': 'bilinear',
 'USE_DROPOUT': True,
 'USE_VISLOGGER': False,
 'VERBOSE': True,
 'WEIGHTS_PATH': '',
 'WEIGHT_DECAY': 0}
INFO: Using fp16 training
Training...
Start looping batches...
using pin_memory on device 0
train Ep 0, Sp 940, loss 0.731127, t print 32.913s, t batch 1.646s
train Ep 0, Sp 1880, loss 0.070593, t print 6.898s, t batch 0.345s
train Ep 0, Sp 2820, loss 0.037716, t print 8.69s, t batch 0.434s
train Ep 0, Sp 3760, loss 0.030432, t print 14.225s, t batch 0.711s
train Ep 0, Sp 4700, loss 0.027741, t print 11.113s, t batch 0.556s
train Ep 0, Sp 5640, loss 0.028779, t print 9.546s, t batch 0.477s
train Ep 0, Sp 6580, loss 0.02786, t print 15.59s, t batch 0.78s
train Ep 0, Sp 7520, loss 0.027917, t print 9.525s, t batch 0.476s
train Ep 0, Sp 8460, loss 0.02431, t print 10.553s, t batch 0.528s
Start looping batches...
using pin_memory on device 0
Traceback (most recent call last):
  File "/home/AR/anaconda3/envs/myenv/bin/ExpRunner", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/AR/TractSeg/bin/ExpRunner", line 202, in <module>
    main()
  File "/home/AR/TractSeg/bin/ExpRunner", line 138, in main
    trainer.train_model(Config, model, data_loader)
  File "/home/AR/TractSeg/tractseg/libs/trainer.py", line 130, in train_model
    probs, metr_batch = model.test(x, y, weight_factor=weight_factor)
  File "/home/AR/TractSeg/tractseg/models/base_model.py", line 188, in test
    outputs = self.net(X)
  File "/home/AR/anaconda3/envs/myenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/AR/TractSeg/tractseg/models/unet_pytorch_deepsup.py", line 73, in forward
    contr_1_1 = self.contr_1_1(inpt)
  File "/home/AR/anaconda3/envs/myenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/AR/anaconda3/envs/myenv/lib/python3.9/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/home/AR/anaconda3/envs/myenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/AR/anaconda3/envs/myenv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 457, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/AR/anaconda3/envs/myenv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 453, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
  File "/home/AR/anaconda3/envs/myenv/lib/python3.9/site-packages/apex/amp/wrap.py", line 21, in wrapper
    args[i] = utils.cached_cast(cast_fn, args[i], handle.cache)
  File "/home/AR/anaconda3/envs/myenv/lib/python3.9/site-packages/apex/amp/utils.py", line 97, in cached_cast
    if cached_x.grad_fn.next_functions[1][0].variable is not x:
IndexError: tuple index out of range
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/AR/anaconda3/envs/myenv/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/home/AR/anaconda3/envs/myenv/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/home/AR/batchgenerators/batchgenerators/dataloading/multi_threaded_augmenter.py", line 92, in results_loop
    raise RuntimeError("Abort event was set. So someone died and we should end this madness. \nIMPORTANT: "
RuntimeError: Abort event was set. So someone died and we should end this madness. 
IMPORTANT: This is not the actual error message! Look further up to see what caused the error. Please also check whether your RAM was full
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/AR/anaconda3/envs/myenv/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/home/AR/anaconda3/envs/myenv/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/home/AR/batchgenerators/batchgenerators/dataloading/multi_threaded_augmenter.py", line 92, in results_loop
    raise RuntimeError("Abort event was set. So someone died and we should end this madness. \nIMPORTANT: "
RuntimeError: Abort event was set. So someone died and we should end this madness. 
IMPORTANT: This is not the actual error message! Look further up to see what caused the error. Please also check whether your RAM was full

```

**Comment by wasserth** [comment]
Unfortunately I am not familiar with this error. A debug option for the training does not exist.

**Comment by mrrestre** [comment]
Hi I figured I was having trouble with APEX and that was causing my IndexError!
