### ISSUE TITLE
Downloading pretrained weights (~140MB) ...Error

### ISSUE THREAD

**Issue by wang-bingh** [MIC-DKFZ/TractSeg#254]
**When I use ‘TractSeg -i hc1_DTI.nii.gz --raw_diffusion_input’ in Teminal to treat example DTI data, the following error continues to appear：**

_Loading weights from: /home/w/.tractseg/pretrained_weights_tract_segmentation_v3.npz
Downloading pretrained weights (~140MB) ...
Traceback (most recent call last):
  File "/home/w/anaconda3/envs/torch/bin/TractSeg", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/w/soft/TractSeg/bin/TractSeg", line 420, in <module>
    main()
  File "/home/w/soft/TractSeg/bin/TractSeg", line 325, in main
    seg = run_tractseg(data, args.output_type,
  File "/home/w/soft/TractSeg/tractseg/python_api.py", line 154, in run_tractseg
    utils.download_pretrained_weights(experiment_type=Config.EXPERIMENT_TYPE,
  File "/home/w/soft/TractSeg/tractseg/libs/utils.py", line 170, in download_pretrained_weights
    download_url(WEIGHTS_URL, weights_path)
  File "/home/w/soft/TractSeg/tractseg/libs/utils.py", line 110, in download_url
    raise e
  File "/home/w/soft/TractSeg/tractseg/libs/utils.py", line 106, in download_url
    r.raise_for_status()
  File "/home/w/anaconda3/envs/torch/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://zenodo.org/record/3518348/files/best_weights_ep220.npz?download=1_

However，the ‘url: https://zenodo.org/record/3518348/files/best_weights_ep220.npz?download=1’ can open and download at Firefox Web Browser. 

 How to solve this problem?

Thank you.

**Comment by wasserth** [comment]
Zenodo did a major update of their website and this also changed the way they accept download requests. I am working on a fix for this.

**Comment by wasserth** [comment]
I fixed the problem and published a new version (v2.9) for pip.

**Comment by wang-bingh** [comment]
Thank you so much for the suggestion! I re-installed  the new version (v2.9) just that and it seems to work fine !

**Comment by wang-bingh** [comment]
Hi Prof  Jakob,
I am getting an error when I use Tractseg to treat **non-HCP data** and I am not sure what it is due to, any suggestions are well appreciated!
Thank you!

The code for **Tract Orientation Maps** that I am running is:
**TractSeg -i tractseg_output/peaks.nii.gz -o tractseg_output --output_type TOM --super_resolution**

Here is the error text:
_/home/w/anaconda3/envs/torch_2023/bin/TractSeg:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').require('TractSeg==2.9')
Loading weights from: /home/w/.tractseg/pretrained_weights_peak_regression_part1_v2.npz
100%|█████████████████████████████████████████| 144/144 [00:02<00:00, 63.55it/s]
Loading weights from: /home/w/.tractseg/pretrained_weights_peak_regression_part2_v2.npz
100%|████████████████████████████████████████| 144/144 [00:01<00:00, 129.27it/s]
Loading weights from: /home/w/.tractseg/pretrained_weights_peak_regression_part3_v2.npz
100%|████████████████████████████████████████| 144/144 [00:01<00:00, 130.46it/s]
Loading weights from: /home/w/.tractseg/pretrained_weights_peak_regression_part4_v2.npz
Traceback (most recent call last):
  File "/home/w/anaconda3/envs/torch_2023/bin/TractSeg", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/w/soft/TractSeg/bin/TractSeg", line 420, in <module>
    main()
  File "/home/w/soft/TractSeg/bin/TractSeg", line 325, in main
    seg = run_tractseg(data, args.output_type,
  File "/home/w/soft/TractSeg/tractseg/python_api.py", line 206, in run_tractseg
    model = BaseModel(Config, inference=True)
  File "/home/w/soft/TractSeg/tractseg/models/base_model.py", line 106, in __init__
    self.load_model(join(self.Config.EXP_PATH, self.Config.WEIGHTS_PATH))
  File "/home/w/soft/TractSeg/tractseg/models/base_model.py", line 280, in load_model
    pytorch_utils.load_checkpoint(path, unet=self.net)
  File "/home/w/soft/TractSeg/tractseg/libs/pytorch_utils.py", line 20, in load_checkpoint
    checkpoint = torch.load(path, map_location=lambda storage, loc: storage)
  File "/home/w/anaconda3/envs/torch_2023/lib/python3.9/site-packages/torch/serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/w/anaconda3/envs/torch_2023/lib/python3.9/site-packages/torch/serialization.py", line 1020, in _legacy_load
    typed_storage._storage._set_from_file(
RuntimeError: unexpected EOF, expected 31322553 more bytes. The file might be corrupted._

The Error in above processing causes further errors when I **run the tracking**：
The code for **tracking** that I am running is:
**Tracking -i tractseg_output/peaks.nii.gz -o tractseg_output**
Here is the further error text:
_/home/w/anaconda3/envs/torch_2023/bin/Tracking:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').require('TractSeg==2.9')
 75%|████████████████████████████████▎          | 54/72 [01:44<00:34,  1.94s/it]
Traceback (most recent call last):
  File "/home/w/anaconda3/envs/torch_2023/lib/python3.9/site-packages/nibabel/loadsave.py", line 100, in load
    stat_result = os.stat(filename)
FileNotFoundError: [Errno 2] No such file or directory: 'tractseg_output/TOM/T_PAR_left.nii.gz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/w/anaconda3/envs/torch_2023/bin/Tracking", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/w/soft/TractSeg/bin/Tracking", line 168, in <module>
    main()
  File "/home/w/soft/TractSeg/bin/Tracking", line 158, in main
    tracking.track(bundle, input_path, Config.PREDICT_IMG_OUTPUT,
  File "/home/w/soft/TractSeg/tractseg/libs/tracking.py", line 179, in track
    tom_peaks_img = nib.load(output_dir + "/" + TOM_folder + "/" + bundle + ".nii.gz")
  File "/home/w/anaconda3/envs/torch_2023/lib/python3.9/site-packages/nibabel/loadsave.py", line 102, in load
    raise FileNotFoundError(f"No such file or no access: '{filename}'")
FileNotFoundError: No such file or no access: 'tractseg_output/TOM/T_PAR_left.nii.gz'_


How to solve this problem? 

Thank you.

**Comment by trinhdh** [comment]
@wasserth Could you please update new https://hub.docker.com/r/wasserth/tractseg_container to the latest version ?
Thank you.

**Comment by rosephamnl** [comment]
@wasserth  hi Jakob, could you please update new https://hub.docker.com/r/wasserth/tractseg_container to the latest version? Thank you!!!

**Comment by anagrammarian** [comment]
I have a workaround for this issue since the container is still old (2+years) and the requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://zenodo.org/record/3518348/files/best_weights_ep220.npz?download=1 error 
occurs when running the singularity or docker container.

So before you run your container, download the weights file using :
wget https://zenodo.org/record/3518348/files/best_weights_ep220.npz?download=1

Move the .npz file from ~/Downloads or wherever it downloaded it to ~/.trackseg/ directory.

Note that you might have to rm -rf ~/.trackseg directory to remove older one with a 0 sized file and recreate a new ~/.trackseg directory using mkdir ~/.trackseg and then move the downloaded ep220.npz file there.

Now run the container. It skips the pulling step and works. Easy peasy.
