### ISSUE TITLE
--super_resolution flag not working

### ISSUE THREAD

**Issue by yasmeme1000** [MIC-DKFZ/TractSeg#273]
I've been able to successfully run TractSeg, however, I want to use the --super_resolution flag to see if it improve the estimation of the fornices. 

The issue is, when I run the exact same comment but with --super_resolution, I receive the following error: 

`TractSeg -i peaks.nii.gz --output_type tract_segmentation -o tractseg_superres --csd_type csd_msmt --super_resolution
Traceback (most recent call last):
  File "/home/gucci/anaconda3/bin/TractSeg", line 420, in <module>
    main()
  File "/home/gucci/anaconda3/bin/TractSeg", line 284, in main
    data_img = img_utils.change_spacing_4D(data_img, new_spacing=1.25)
  File "/home/gucci/anaconda3/lib/python3.10/site-packages/tractseg/libs/img_utils.py", line 534, in change_spacing_4D
    res = affine_map.transform(data[:, :, :, i], interp="nearest")
TypeError: AffineMap.transform() got an unexpected keyword argument 'interp'

I've tried installing and re-installing all dependencies, but still no luck. The referenced script section is below: 

`    # copy very important; otherwise new_affine changes will also be in old affine
    new_affine = np.copy(img_in.affine)
    new_affine[0, 0] = new_spacing if img_in.affine[0, 0] > 0 else -new_spacing
    new_affine[1, 1] = new_spacing if img_in.affine[1, 1] > 0 else -new_spacing
    new_affine[2, 2] = new_spacing if img_in.affine[2, 2] > 0 else -new_spacing

    new_shape = np.floor(np.array(img_in.get_fdata().shape) * (img_spacing / new_spacing))
    new_shape = new_shape[:3]  # drop last dim

    new_data = []
    for i in range(data.shape[3]):
        affine_map = AffineMap(np.eye(4),
                               new_shape, new_affine,
                               old_shape, img_in.affine
                               )
        # Generally "nearest" a bit better results than "linear" interpolation
        res = affine_map.transform(data[:, :, :, i], interp="nearest")
        new_data.append(res)

    new_data = np.array(new_data).transpose(1, 2, 3, 0)
    img_new = nib.Nifti1Image(new_data, new_affine)

    return img_new`
`

**Comment by wasserth** [comment]
The super_resolution feature is not actively being used anymore. Probably it would be better to remove it completely. I would recommend to not use it.
