### ISSUE TITLE
plot_tractometry_results - IndexError: index 54 is out of bounds for axis 0 with size 50

### ISSUE THREAD

**Issue by giovannividetta** [MIC-DKFZ/TractSeg#281]
Hello, @wasserth!

I have issues with _plot_tractometry_results_ . When I run the last step of Tractometry analysis, the script crashes if I would plot all 50 fascicles segmented and listed in _All_tractometry_ vector.

I reported the error as follows.

**plot_tractometry_results -i subjects_con_dep.txt -o tractometry_result_con_dep.png
Correcting for comparison of multiple tracts: False
Doing group analysis.
Number of subjects:
  group 0: 20
  group 1: 18
Traceback (most recent call last):
  File "/home/utente/Password2024/envs/python39/bin/plot_tractometry_results", line 386, in <module>
    main()
  File "/home/utente/Password2024/envs/python39/bin/plot_tractometry_results", line 377, in main
    plot_tractometry_with_pvalue(values, meta_data, all_bundles, selected_bundles, args.output_path,
  File "/home/utente/Password2024/envs/python39/bin/plot_tractometry_results", line 144, in plot_tractometry_with_pvalue
    values = correct_for_confounds(values, meta_data, bundles, selected_bun_indices, NR_POINTS, analysis_type,
  File "/home/utente/Password2024/envs/python39/bin/plot_tractometry_results", line 77, in correct_for_confounds
    target = np.array([values[s][b_idx][jdx] for s in meta_data["subject_id"]])[..., None]  # [samples, 1]
  File "/home/utente/Password2024/envs/python39/bin/plot_tractometry_results", line 77, in <listcomp>
    target = np.array([values[s][b_idx][jdx] for s in meta_data["subject_id"]])[..., None]  # [samples, 1]
IndexError: index 54 is out of bounds for axis 0 with size 50**

I also attached file [subjects_con_dep.txt](https://github.com/user-attachments/files/18109916/subjects_con_dep.txt) used in _plot_tractometry_results_ .

Just to let you know, if I selected a number of fascicles to plot, the script works without problems.

Thank you for your support!

**Comment by giovannividetta** [comment]
Solved! I re-downloaded the script and now it works!
