### ISSUE TITLE
nibabel.py3k.filenotfounderror in docker

### ISSUE THREAD

**Issue by caffeNewbie** [MIC-DKFZ/TractSeg#37]
Hello,

I'm using Docker Toolbox for Windows 7 to access TractSeg. The command does not read the input file when using tractsegcontainer:master and gives errors same as [this user](https://github.com/MIC-DKFZ/TractSeg/issues/2) when using tractsegcontainer:v1.4. 

I am a bit stumped since I am using Docker (containing all pre-requisites) but still getting these errors.

Would be glad if you could help with this!

Output screens:

```
docker@default:~$ ls /home/docker/tractseg
dwi.bvals   dwi.bvecs   dwi.nii.gz
docker@default:~$
```

```
docker@default:~$ sudo docker run -v /home/docker/tractseg -t wasserth/tractseg
 _container:master TractSeg -i dwi.nii.gz --preprocess
INFO: font search path ['/usr/local/lib/python2.7/dist-packages/matplotlib/mpl-d
 ata/fonts/ttf', '/usr/local/lib/python2.7/dist-packages/matplotlib/mpl-data/font
 s/afm', '/usr/local/lib/python2.7/dist-packages/matplotlib/mpl-data/fonts/pdfcor
 efonts']
 INFO: generated new fontManager
 Traceback (most recent call last):
   File "/usr/local/bin/TractSeg", line 370, in <module>
     main()
   File "/usr/local/bin/TractSeg", line 252, in main
     data_img = nib.load(peak_path)
   File "/usr/local/lib/python2.7/dist-packages/nibabel/loadsave.py", line 42, in
  load
     raise FileNotFoundError("No such file or no access: '%s'" % filename)
 nibabel.py3k.FileNotFoundError: No such file or no access: 'dwi.nii.gz'
 docker@default:~$

```
```
docker@default:~$ sudo docker run -v /home/docker/tractseg -t wasserth/tractseg
_container:v1.4 TractSeg -i dwi.nii.gz --preprocess
usage: TractSeg [-h] -i filepath [-o directory] [--output_multiple_files]
                [--csd_type csd|csd_msmt|csd_msmt_5tt]
                [--output_type tract_segmentation|endings_segmentation|TOM|dm_re
gression]
                [--bvals filename] [--bvecs filename] [--brain_mask filename]
                [--verbose] [--skip_peak_extraction]
                [--keep_intermediate_files] [--preview] [--flip]
                [--single_orientation] [--bundle_specific_threshold]
                [--get_probabilities] [--version]
TractSeg: error: unrecognized arguments: --preprocess
docker@default:~$
```

```
docker@default:~$ sudo docker run -v /home/docker/tractseg -t wasserth/tractseg
_container:v1.4 TractSeg -i dwi.nii.gz
Creating brain mask...

Error: input image dwi not valid

rm: cannot remove 'tractseg_output/nodif_brain_mask.nii.gz': No such file or dir
ectory
mv: cannot stat 'tractseg_output/nodif_brain_mask_mask.nii.gz': No such file or
directory
Creating peaks (1 of 3)...
dwi2response: [ERROR] Command failed: mrconvert /dwi.nii.gz - -strides 0,0,0,1 -
fslgrad /dwi.bvecs /dwi.bvals | dwiextract - /dwi2response-tmp-7QS2GT/dwi.mif -s
ingleshell -no_bzero (dwi2response:84)
dwi2response: Output of failed command:
              mrconvert: [ERROR] input file "/dwi.bvecs" for option "-fslgrad" n
ot found
              dwiextract: [ERROR] no filename supplied to standard input (broken
 pipe?)
              dwiextract: [ERROR] error opening image "-"
dwi2response: Script failed while executing the command: mrconvert /dwi.nii.gz -
 -strides 0,0,0,1 -fslgrad /dwi.bvecs /dwi.bvals | dwiextract - /dwi2response-tm
p-7QS2GT/dwi.mif -singleshell -no_bzero
dwi2response: For debugging, inspect contents of temporary directory: /dwi2respo
nse-tmp-7QS2GT/
Creating peaks (2 of 3)...
dwi2fod: [ERROR] input file "dwi.bvecs" for option "-fslgrad" not found
Creating peaks (3 of 3)...
sh2peaks: [ERROR] failed to open key/value file "tractseg_output/WM_FODs.mif": N
o such file or directory
sh2peaks: [ERROR] error opening image "tractseg_output/WM_FODs.mif"
Traceback (most recent call last):
  File "/usr/local/bin/TractSeg", line 113, in <module>
    data_img = nib.load(join(HP.PREDICT_IMG_OUTPUT, "peaks.nii.gz"))
  File "/usr/local/lib/python2.7/dist-packages/nibabel/loadsave.py", line 42, in
 load
    raise FileNotFoundError("No such file or no access: '%s'" % filename)
nibabel.py3k.FileNotFoundError: No such file or no access: 'tractseg_output/peak
s.nii.gz'
docker@default:~$

```

Please do let me know if you need more information. Thanks!

**Comment by wasserth** [comment]
Seems it does not find the input file because it was not specified correctly. Try the following 
`sudo docker run -v /home/docker/tractseg:/data -t wasserth/tractseg
 _container:master TractSeg -i /data/dwi.nii.gz -o /data --raw_diffusion_input`.
(note: `--preview` is replaced by `--raw_diffusion_input`)

**Comment by caffeNewbie** [comment]
Thanks, that seems to have solved it - I had understood the command to be specifying the directory structure and that /data was only part of it. However, although the image is being read now, dwi2response command gives errors.

```
docker@default:~$ sudo docker run -v /home/docker/tractseg:/data -t wasserth/tr
actseg_container:master TractSeg -i /data/dwi.nii.gz -o /data --raw_diffusion_i
nput
INFO: font search path ['/usr/local/lib/python2.7/dist-packages/matplotlib/mpl-d
ata/fonts/ttf', '/usr/local/lib/python2.7/dist-packages/matplotlib/mpl-data/font
s/afm', '/usr/local/lib/python2.7/dist-packages/matplotlib/mpl-data/fonts/pdfcor
efonts']
INFO: generated new fontManager
Creating brain mask...
Creating peaks (1 of 3)...
dwi2response: [ERROR] Command failed: mrconvert /data/dwi.nii.gz - -strides 0,0,
0,1 -fslgrad /data/dwi.bvecs /data/dwi.bvals | dwiextract - /dwi2response-tmp-Q2
SJZW/dwi.mif -singleshell -no_bzero (dwi2response:84)
dwi2response: Output of failed command:
              mrconvert: [ERROR] bvecs file must contain exactly 3 rows or colum
ns (file "/data/dwi.bvecs" has 55)
              mrconvert: [ERROR] error importing diffusion gradient table for im
age "/data/dwi.nii.gz"
              dwiextract: [ERROR] no filename supplied to standard input (broken
 pipe?)
              dwiextract: [ERROR] error opening image "-"
dwi2response: Script failed while executing the command: mrconvert /data/dwi.nii
.gz - -strides 0,0,0,1 -fslgrad /data/dwi.bvecs /data/dwi.bvals | dwiextract - /
dwi2response-tmp-Q2SJZW/dwi.mif -singleshell -no_bzero
dwi2response: For debugging, inspect contents of temporary directory: /dwi2respo
nse-tmp-Q2SJZW/
Creating peaks (2 of 3)...
dwi2fod: [ERROR] bvecs file must contain exactly 3 rows or columns (file "/data/
dwi.bvecs" has 55)
dwi2fod: [ERROR] error importing diffusion gradient table for image "/data/dwi.n
ii.gz"
Creating peaks (3 of 3)...
sh2peaks: [ERROR] cannot access file "/data/tractseg_output/WM_FODs.nii.gz": No
such file or directory
sh2peaks: [ERROR] error opening image "/data/tractseg_output/WM_FODs.nii.gz"
Traceback (most recent call last):
  File "/usr/local/bin/TractSeg", line 370, in <module>
    main()
  File "/usr/local/bin/TractSeg", line 246, in main
    data_img = nib.load(peak_path)
  File "/usr/local/lib/python2.7/dist-packages/nibabel/loadsave.py", line 42, in
 load
    raise FileNotFoundError("No such file or no access: '%s'" % filename)
nibabel.py3k.FileNotFoundError: No such file or no access: '/data/tractseg_outpu
t/peaks.nii.gz'
docker@default:~$
```

My number of diffusion directions is 48 + 5 with no diffusion weighting. 

Can I also ask why the bvals and bvecs files need to have the extensions .bvals and .bvecs? The images I generate using dicom2niix have the extensions .bval and .bvec (without the 's'). I had to manually rename the extensions to make them .bvals and .bvecs - could this be why dwi2response is not reading them?

**Comment by caffeNewbie** [comment]
Oh, never mind! The .bvals and .bvecs files were modified my previous attempts at running the docker commands. I copy-pasted the original ones and everything is working now.

But I do wanted to ask why .bvals and .bvecs are expected instead of .bval and .bvec

**Comment by wasserth** [comment]
Great that it works.  
You can give different names to your bvals and bvecs file. But then you have to tell TractSeg their names by setting the parameters `--bvals my_file.whatever` and `--bvecs something.else`.

**Comment by ArkaJU** [comment]
I am facing the same issue, trying to run it on Ubuntu 18.04.2 LS and running this:
```
sudo docker run -v /absolute/path/to/my/data/directory:/data \
t wasserth/tractseg_container:master TractSeg -i /data/my_diffusion_file.nii.gz -o /data --raw_diffusion_input
```
and getting this:
``` 
Creating brain mask...

Error: input image /data/my_diffusion_file not valid

rm: cannot remove '/data/nodif_brain_mask.nii.gz': No such file or directory
mv: cannot stat '/data/nodif_brain_mask_mask.nii.gz': No such file or directory
Creating peaks (1 of 3)...
dwi2response: [ERROR] Command failed: mrconvert /data/my_diffusion_file.nii.gz - -strides 0,0,0,1 -fslgrad /data/my_diffusion_file.bvecs /data/my_diffusion_file.bvals | dwiextract - /dwi2response-tmp-OD6U2E/dwi.mif -singleshell -no_bzero (dwi2response:84)
dwi2response: Output of failed command:
              mrconvert: [ERROR] input file "/data/my_diffusion_file.bvecs" for option "-fslgrad" not found
              dwiextract: [ERROR] no filename supplied to standard input (broken pipe?)
              dwiextract: [ERROR] error opening image "-"
dwi2response: Script failed while executing the command: mrconvert /data/my_diffusion_file.nii.gz - -strides 0,0,0,1 -fslgrad /data/my_diffusion_file.bvecs /data/my_diffusion_file.bvals | dwiextract - /dwi2response-tmp-OD6U2E/dwi.mif -singleshell -no_bzero
dwi2response: For debugging, inspect contents of temporary directory: /dwi2response-tmp-OD6U2E/
Creating peaks (2 of 3)...
dwi2fod: [ERROR] input file "/data/my_diffusion_file.bvecs" for option "-fslgrad" not found
Creating peaks (3 of 3)...
sh2peaks: [ERROR] cannot access file "/data/WM_FODs.nii.gz": No such file or directory
sh2peaks: [ERROR] error opening image "/data/WM_FODs.nii.gz"
Traceback (most recent call last):
  File "/usr/local/bin/TractSeg", line 378, in <module>
    main()
  File "/usr/local/bin/TractSeg", line 249, in main
    data_img = nib.load(peak_path)
  File "/usr/local/lib/python2.7/dist-packages/nibabel/loadsave.py", line 42, in load
    raise FileNotFoundError("No such file or no access: '%s'" % filename)
nibabel.py3k.FileNotFoundError: No such file or no access: '/data/peaks.nii.gz
```
What is the exact solution? Can anybody please help?

**Comment by wasserth** [comment]
You apparently have problems accessing the docker image. 
Does this command work?
```
sudo docker pull wasserth/tractseg_container:master 
```

**Comment by ArkaJU** [comment]
Yes it does, shows the following:
```
master: Pulling from wasserth/tractseg_container
a4d8138d0f6b: Already exists 
2c9df2af9276: Already exists 
009e5a661ad5: Already exists 
cf00c752c38c: Already exists 
f1888be1e1ac: Already exists 
79c4e891d07a: Already exists 
57f047fd10de: Pull complete 
ecf95563839f: Pull complete 
cd5b1715c31e: Pull complete 
88ee53250a14: Pull complete 
6f0b857f7a1d: Pull complete 
1ae17fbc5d8f: Pull complete 
0d1923afa3f4: Pull complete 
c8abb8f280cf: Pull complete 
7ec89ff19fc2: Pull complete 
d89bebfa2a0e: Pull complete 
Digest: sha256:c951d96185b764743b81478230b850c0cb2e38da91f59e2ec236407fc786076f
Status: Downloaded newer image for wasserth/tractseg_container:master
```
But I still get the same error.
```
sudo docker run -v /home/docker/tractseg:/data -t wasserth/tractseg _container:master TractSeg -i /data/Diffusion.nii.gz -o /data --raw_diffusion_input

```
The command is fine right? What could be the reason then?

**Comment by wasserth** [comment]
There is a whitespace in the command (between tractseg and _container). Try this:
```
sudo docker run -v /home/docker/tractseg:/data -t wasserth/tractseg_container:master TractSeg -i /data/Diffusion.nii.gz -o /data --raw_diffusion_input

```

**Comment by ArkaJU** [comment]
It runs this time but gives the following error:
```
Creating brain mask...

Error: input image /data/Diffusion not valid

rm: cannot remove '/data/nodif_brain_mask.nii.gz': No such file or directory
mv: cannot stat '/data/nodif_brain_mask_mask.nii.gz': No such file or directory
Creating peaks (1 of 3)...
dwi2response: [ERROR] Command failed: mrconvert /data/Diffusion.nii.gz - -strides 0,0,0,1 -fslgrad /data/Diffusion.bvecs /data/Diffusion.bvals | dwiextract - /dwi2response-tmp-FUA9JN/dwi.mif -singleshell -no_bzero (dwi2response:84)
dwi2response: Output of failed command:
              mrconvert: [ERROR] input file "/data/Diffusion.bvecs" for option "-fslgrad" not found
              dwiextract: [ERROR] no filename supplied to standard input (broken pipe?)
              dwiextract: [ERROR] error opening image "-"
dwi2response: Script failed while executing the command: mrconvert /data/Diffusion.nii.gz - -strides 0,0,0,1 -fslgrad /data/Diffusion.bvecs /data/Diffusion.bvals | dwiextract - /dwi2response-tmp-FUA9JN/dwi.mif -singleshell -no_bzero
dwi2response: For debugging, inspect contents of temporary directory: /dwi2response-tmp-FUA9JN/
Creating peaks (2 of 3)...
dwi2fod: [ERROR] input file "/data/Diffusion.bvecs" for option "-fslgrad" not found
Creating peaks (3 of 3)...
sh2peaks: [ERROR] cannot access file "/data/WM_FODs.nii.gz": No such file or directory
sh2peaks: [ERROR] error opening image "/data/WM_FODs.nii.gz"
Traceback (most recent call last):
  File "/usr/local/bin/TractSeg", line 378, in <module>
    main()
  File "/usr/local/bin/TractSeg", line 249, in main
    data_img = nib.load(peak_path)
  File "/usr/local/lib/python2.7/dist-packages/nibabel/loadsave.py", line 42, in load
    raise FileNotFoundError("No such file or no access: '%s'" % filename)
nibabel.py3k.FileNotFoundError: No such file or no access: '/data/peaks.nii.gz'
```

**Comment by wasserth** [comment]
Does it work if you run `bet` directly on the Diffusion data? You need to have FSL installed for that. `bet` is a FSL tool for creating brain masks which is used by TractSeg.
```
bet Diffusion nodif_brain_mask.nii.gz -f 0.3 -g 0 -m
```

**Comment by ArkaJU** [comment]
I am not able to install FSL, is there some other way?

**Comment by wasserth** [comment]
The error seems to come from FSL bet. Without FSL installed to try it out it is difficult to track down the problem.
