### ISSUE TITLE
An RuntimeError occurred when I used python interface.

### ISSUE THREAD

**Issue by luqily** [MIC-DKFZ/TractSeg#43]
Hi.
When I used python interface, the RuntimeError occurred.

`import nibabel as nib`
`import numpy as np` 
`from tractseg.python_api import run_tractseg`
`peaks = nib.load("tests/reference_files/peaks.nii.gz").get_data()`
`segmentation = run_tractseg(peaks)`

Loading weights from: /home/qilu/.tractseg/pretrained_weights_tract_segmentation_v2.npz
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "tractseg/python_api.py", line 168, in run_tractseg
    model = BaseModel(Config)
  File "tractseg/models/base_model.py", line 116, in __init__
    self.load_model(join(self.Config.EXP_PATH, self.Config.WEIGHTS_PATH))
  File "tractseg/models/base_model.py", line 294, in load_model
    pytorch_utils.load_checkpoint(path, unet=self.net)
  File "tractseg/libs/pytorch_utils.py", line 36, in load_checkpoint
    checkpoint = torch.load(path, map_location=lambda storage, loc: storage)
  File "/home/qilu/anaconda2/envs/pytorch/lib/python2.7/site-packages/torch/serialization.py", line 368, in load
    return _load(f, map_location, pickle_module)
  File "/home/qilu/anaconda2/envs/pytorch/lib/python2.7/site-packages/torch/serialization.py", line 549, in _load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: unexpected EOF, expected 5801749 more bytes. The file might be corrupted.

How should I modify it?

**Comment by wasserth** [comment]
Seems like the weights file is corrupted. Try to delete everything inside of `~/.tractseg` and then run again. It should download the weights file automatically. It should show `Downloading pretrained weights (~140MB) ...`.

**Comment by luqily** [comment]
@wasserth 
Thanks for your reply! It solved my problem.
