### ISSUE TITLE
Hello, what's wrong with reporting this error when typing the instruction "TractSeg"

### ISSUE THREAD

**Issue by zlf123-marker** [MIC-DKFZ/TractSeg#58]
Traceback (most recent call last):
  File "/home/zlf/anaconda3/envs/TractSeg/bin/TractSeg", line 38, in <module>
    from tractseg.libs import mrtrix
  File "/home/zlf/anaconda3/envs/TractSeg/lib/python3.6/site-packages/tractseg/libs/mrtrix.py", line 29, in <module>
    from tractseg.libs import tracking
  File "/home/zlf/anaconda3/envs/TractSeg/lib/python3.6/site-packages/tractseg/libs/tracking.py", line 9, in <module>
    from dipy.tracking.utils import move_streamlines
ImportError: cannot import name 'move_streamlines'
(TractSeg) zlf@aiserver:~$ TractSeg -i Diffusion.nii.gz --raw_diffusion_input
Traceback (most recent call last):
  File "/home/zlf/anaconda3/envs/TractSeg/bin/TractSeg", line 38, in <module>
    from tractseg.libs import mrtrix
  File "/home/zlf/anaconda3/envs/TractSeg/lib/python3.6/site-packages/tractseg/libs/mrtrix.py", line 29, in <module>
    from tractseg.libs import tracking
  File "/home/zlf/anaconda3/envs/TractSeg/lib/python3.6/site-packages/tractseg/libs/tracking.py", line 9, in <module>
    from dipy.tracking.utils import move_streamlines
ImportError: cannot import name 'move_streamlines'

**Comment by wasserth** [comment]
You are probably using dipy 1.0 with an older version of TractSeg. You can either use dipy 1.0 and the newest version of TractSeg:
```
pip install https://github.com/MIC-DKFZ/TractSeg/archive/master.zip
```
Or you can use an older version of TractSeg but then you also have to install an older version of dipy (<1.0).

I recommend installing the newest version of TractSeg.

**Comment by zlf123-marker** [comment]
Ok, thank you very much，I would also like to ask what are the prerequisites for installing a new version of Linux?Or just any version?

**Comment by wasserth** [comment]
TractSeg should be fine with any version of Linux.

**Comment by zlf123-marker** [comment]
Ok, thank you very much
