### ISSUE TITLE
New plot_tractometry code errros

### ISSUE THREAD

**Issue by caffeNewbie** [MIC-DKFZ/TractSeg#74]
Hi, I'm using TractSeg 2.1 and the plot_tractometry_results.py code that comes with it. I have the path to my subjects in a text file like this:

```
# tractometry_path=/home/fsluser/Documents/images/SUBJECT_ID/tractometry.csv
#bundles=CC

subject_id group age
subject1 0 87
.......
```
When I run the file plot_tractometry_results.py, I get an error:

```
Traceback (most recent call last):
  File "/usr/local/bin/plot_tractometry_results", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/fsluser/TractSeg-2.1/bin/plot_tractometry_results", line 279, in <module>
    main()
  File "/home/fsluser/TractSeg-2.1/bin/plot_tractometry_results", line 275, in main
    show_detailed_p, nperm=nperm)
  File "/home/fsluser/TractSeg-2.1/bin/plot_tractometry_results", line 130, in plot_tractometry_with_pvalue
    confound_names)
  File "/home/fsluser/TractSeg-2.1/bin/plot_tractometry_results", line 62, in correct_for_confounds
    target = np.array([values[s][b_idx][jdx] for s in meta_data["subject_id"]])
  File "/home/fsluser/TractSeg-2.1/bin/plot_tractometry_results", line 62, in <listcomp>
    target = np.array([values[s][b_idx][jdx] for s in meta_data["subject_id"]])
IndexError: invalid index to scalar variable.
```

When I print the contents of `values[meta_data["subject_id"][0]]`, it gives:

```
[0.14110962 0.27532917 0.36702716 0.40695012 0.39713436 0.37795281
 0.39438459 0.46790785 0.59614235 0.66779399 0.66251832 0.64867043
 0.58077657 0.44441885 0.38852283 0.39819279 0.40886423 0.38063154
 0.281654   0.15169801]
```
I understand why the error is, since the array has only one dimension. I tried to change several things to see if it works, but the function `metric_utils.unconfound()` in line 64 seems to expect an array of a certain size and shape. 

Could you help with this error please?

Thanks.

**Comment by wasserth** [comment]
Did you try with more than one bundle? Maybe this solves the problem.
So replace the second line by e.g.
```
# bundles=CG_left CST_right
```
The bundle `CC` should anyways not be working with Tractometry as documented here: https://github.com/MIC-DKFZ/TractSeg/blob/master/resources/Tractometry_documentation.md

There was also a minor update to 2.1 one or two days after its release. So you might also want to do 
```
pip install --upgrade https://github.com/MIC-DKFZ/TractSeg/archive/v2.1.zip
```
