### ISSUE TITLE
plot_tractometry_results fails if trailling spaces are present in the columns of subjects.txt

### ISSUE THREAD

**Issue by dellani** [MIC-DKFZ/TractSeg#97]
The program fails to run if the text file describing the statistical analysis (subjects.txt in the examples included with the software) contains trailing spaces in the columns. It interprets the trailing spaces as an extra column, leading to the following error message:

>  $: python3 -m pdb ~/.local/bin/plot_tractometry_results -i subjects.txt -o tractometry_result.png --mc
> /home/jusers/dellani/.local/bin/plot_tractometry_results(3)<module>()
-> import argparse
(Pdb) continue
Correcting for comparison of multiple tracts: True
Using 6 manually specified bundles.
Doing group analysis.
Number of subjects:
  group 0: 1
  group 1: 1
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/pdb.py", line 1667, in main
    pdb._runscript(mainpyfile)
  File "/usr/local/lib/python3.6/pdb.py", line 1548, in _runscript
    self.run(statement)
  File "/usr/local/lib/python3.6/bdb.py", line 434, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/home/dellani/.local/bin/plot_tractometry_results", line 3, in <module>
    import argparse
  File "/home/dellani/.local/bin/plot_tractometry_results", line 275, in main
    show_detailed_p, nperm=nperm)
  File "/home/dellani/.local/bin/plot_tractometry_results", line 130, in plot_tractometry_with_pvalue
    confound_names)
  File "/home/dellani/.local/bin/plot_tractometry_results", line 65, in correct_for_confounds
    group_data=True)
  File "/home/dellani/.local/lib/python3.6/site-packages/tractseg/libs/metric_utils.py", line 376, in unconfound
    lr = LinearRegression(fit_intercept=True).fit(confound, y)  # lr.coef_: [targets, confounds]
  File "/home/dellani/.local/lib/python3.6/site-packages/sklearn/linear_model/_base.py", line 492, in fit
    y_numeric=True, multi_output=True)
  File "/home/dellani/.local/lib/python3.6/site-packages/sklearn/utils/validation.py", line 755, in check_X_y
    estimator=estimator)
  File "/home/dellani/.local/lib/python3.6/site-packages/sklearn/utils/validation.py", line 578, in check_array
    allow_nan=force_all_finite == 'allow-nan')
  File "/home/dellani/.local/lib/python3.6/site-packages/sklearn/utils/validation.py", line 60, in _assert_all_finite
    msg_dtype if msg_dtype is not None else X.dtype)
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /home/dellani/.local/lib/python3.6/site-packages/sklearn/utils/validation.py(60)_assert_all_finite()
-> msg_dtype if msg_dtype is not None else X.dtype)
(Pdb) p X
array([[ 0. , 40.1,  0. ,  nan],
       [ 1. , 45.2,  0. ,  nan]])
(Pdb)

**Comment by wasserth** [comment]
Thanks for pointing this out. I am using pandas to parse the subjects.txt file as a space-separated csv file. Unfortunately pandas is getting these trailing spaces wrong. So far I have not found an easy solution for getting pandas to do this correctly.
I will definitely update the documentation to make people aware of this danger.

**Comment by dellani** [comment]
Not for that! May be I will have time to look at that and can put a merge request with the solution. Meanwhile, it is good to have the bug documented here for the newcomers :-)
