### ISSUE TITLE
Error message using docker version

### ISSUE THREAD

**Issue by ealvaredo** [MIC-DKFZ/TractSeg#99]
Hello! I would like to share an error that I am getting wher use the docker version

The command is the following

sudo docker run -v /myfolder:/data -t tractseg_container:latest TractSeg -i /data/tractseg_output/peaks.nii.gz -o /data/tractseg_output --output_type TOM

I have this message:

Loading weights from: /root/.tractseg/pretrained_weights_peak_regression_part1_v2.npz
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 144/144 [00:31<00:00,  4.57it/s]
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/joblib/externals/loky/process_executor.py", line 418, in _process_worker
    r = call_item()
  File "/usr/local/lib/python3.5/dist-packages/joblib/externals/loky/process_executor.py", line 272, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.5/dist-packages/joblib/_parallel_backends.py", line 608, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/joblib/parallel.py", line 256, in __call__
    for func, args, kwargs in self.items]
  File "/usr/local/lib/python3.5/dist-packages/joblib/parallel.py", line 256, in <listcomp>
    for func, args, kwargs in self.items]
  File "/usr/local/lib/python3.5/dist-packages/tractseg/libs/peak_utils.py", line 267, in _process_bundle
    bundle_peaks[mask == 0] = 0
IndexError: boolean index did not match indexed array along dimension 0; dimension is 194 but corresponding boolean dimension is 258
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/TractSeg", line 400, in <module>
    main()
  File "/usr/local/bin/TractSeg", line 321, in main
    unit_test=args.test)
  File "/usr/local/lib/python3.5/dist-packages/tractseg/python_api.py", line 242, in run_tractseg
    TOM_dilation, nr_cpus=nr_cpus)
  File "/usr/local/lib/python3.5/dist-packages/tractseg/libs/peak_utils.py", line 273, in mask_and_normalize_peaks
    for idx, bundle in enumerate(bundles))
  File "/usr/local/lib/python3.5/dist-packages/joblib/parallel.py", line 1017, in __call__
    self.retrieve()
  File "/usr/local/lib/python3.5/dist-packages/joblib/parallel.py", line 909, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/usr/local/lib/python3.5/dist-packages/joblib/_parallel_backends.py", line 562, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 405, in result
    return self.__get_result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
IndexError: boolean index did not match indexed array along dimension 0; dimension is 194 but corresponding boolean dimension is 258

Any Idea? Thanks in advance!

**Comment by wasserth** [comment]
Hello,
does your brain mask have the same dimensions as your peaks image and is it in the same space (the affine is the same) ?
